### ISSUE TITLE
My terminal prompt stuck at startup.

### ISSUE THREAD

**Issue by MuhmdRaouf** [zdharma/zinit#119]
Hey i am using Zplugin and i am super happy with it, my terminal startup has become so fast which is amazing, but i have one problem that at the startup my terminal freeze like for couple seconds, every thing i wrote appear all at once, and all the completion [_files] in my PATH and keep showing in autosuggestion, i don't know is that because of my configs or its something related to Zplugin, it would be nice if someone could help me out here.

![Screen Recording 2019-03-23 at 9 48 42 AM](https://user-images.githubusercontent.com/10425180/54863889-0f8e7a80-4d57-11e9-9e43-6ca0ec5f9be2.gif)

work on multiple project with different languages and i keep go back and forth between them that's why the variety of the language plugins in case if somebody asking 
that's my .zshrc : 

```
# zmodload zsh/zprof #Debugging Technique 
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#"""                              Shell Settings                              """
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh/.zsh_history"
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
COMPLETION_WAITING_DOTS="true"
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first  # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#"""                                ZPlugin                                   """
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# I can"t remember the ZPLG home variable - change this to your install location
ZSH="$HOME/.zplugin/plugins/robbyrussell---oh-my-zsh/"

# OMZ things to source
local _ZSHRC_OMZ_SOURCES=(
  # Libs
  lib/compfix.zsh
  lib/completion.zsh
  lib/functions.zsh
  lib/diagnostics.zsh
  lib/grep.zsh
  lib/key-bindings.zsh
  lib/misc.zsh
  lib/spectrum.zsh
  lib/termsupport.zsh

  # Plugins
  plugins/aws/aws.plugin.zsh
  plugins/bundler/bundler.plugin.zsh
  plugins/colored-man-pages/colored-man-pages.plugin.zsh
  plugins/command-not-found/command-not-found.plugin.zsh
  plugins/composer/composer.plugin.zsh
  plugins/django/django.plugin.zsh
  plugins/docker-compose/docker-compose.plugin.zsh
  plugins/docker-machine/docker-machine.plugin.zsh
  plugins/dotenv/dotenv.plugin.zsh
  plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
  plugins/git/git.plugin.zsh
  plugins/golang/golang.plugin.zsh
  plugins/jenv/jenv.plugin.zsh
  plugins/laravel/laravel.plugin.zsh
  plugins/npm/npm.plugin.zsh
  plugins/rake-fast/rake-fast.plugin.zsh
  plugins/rbenv/rbenv.plugin.zsh
  plugins/react-native/react-native.plugin.zsh
  plugins/tmux/tmux.plugin.zsh
  plugins/vscode/vscode.plugin.zsh
)

zplugin ice wait"0" from"gh" pick"lib/git.zsh" nocompletions blockf \
  atload'!local f; for f in ${_ZSHRC_OMZ_SOURCES}; do source $f; done' \
  compile"(${(j.|.)_ZSHRC_OMZ_SOURCES})" lucid
zplugin light robbyrussell/oh-my-zsh

zplugin ice wait"0" lucid
zplugin light zsh-users/zsh-completions

zplugin ice wait"0" atload"_zsh_autosuggest_start" lucid
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait"0" atinit"zpcompinit" lucid
zplugin light zdharma/fast-syntax-highlighting

zplugin ice wait"1" as"completion" lucid
zplugin snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

zplugin ice wait"1" as"completion" lucid
zplugin snippet OMZ::plugins/adb/_adb

export NVM_LAZY_LOAD=true
zplugin ice wait"1" lucid
zplugin light lukechilds/zsh-nvm

zplugin ice wait"1" as"program" pick"bin/git-dsf" lucid
zplugin light zdharma/zsh-diff-so-fancy

zplugin ice wait"1" lucid
zplugin light zdharma/history-search-multi-word

zplugin ice wait"1" lucid
zplugin light zsh-users/zsh-history-substring-search
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#"""                                Theme                                     """
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user ssh dir_writable dir vcs newline status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(rbenv virtualenv command_execution_time background_jobs time battery ram node_version)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_IGNORE_TERM_COLORS=true

# Dirs
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="black"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="magenta"

# VCS
POWERLEVEL9K_VCS_GIT_ICON="\uF408 "
POWERLEVEL9K_VCS_GIT_GITHUB_ICON="\uF408 "

# Time
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M %d/%m/%Y}"

# Node Version
P9K_NODE_VERSION_PROJECT_ONLY="true"
POWERLEVEL9K_NODE_VERSION_BACKGROUND="seagreen1"
POWERLEVEL9K_NODE_VERSION_FOREGROUND="grey30"

#rbenv 
POWERLEVEL9K_RBENV_FOREGROUND="white"

# Battery
POWERLEVEL9K_BATTERY_CHARGING="yellow"
POWERLEVEL9K_BATTERY_CHARGED="green"
POWERLEVEL9K_BATTERY_DISCONNECTED="$DEFAULT_COLOR"
POWERLEVEL9K_BATTERY_LOW_THRESHOLD="10"
POWERLEVEL9K_BATTERY_LOW_COLOR="red"

zplugin light romkatv/powerlevel10k
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#"""                            Auto Completion                               """
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip
compctl -K _pip_completion pip3
# pip zsh completion end

#pipenv zsh completion start
_pipenv() {
  eval $(env COMMANDLINE="${words[1,$CURRENT]}" _PIPENV_COMPLETE=complete-zsh  pipenv)
}
if [[ "$(basename -- ${(%):-%x})" != "_pipenv" ]]; then
  autoload -U compinit && compinit
  compdef _pipenv pipenv
fi
# pipenv zsh completion end
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#"""                                Aliases                                   """
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
# Colorls Aliases:
alias ls="colorls"
alias ll="colorls -al"
alias l="colorls -l"

#Django Aliases:
alias runserver="python manage.py runserver"
alias makemigrations="python manage.py makemigrations"
alias migrate="python manage.py migrate"
alias django-test="python manage.py test"
alias startapp="python manage.py startapp"
alias createsuperuser="python manage.py createsuperuser"
alias rm-migrations="rm $(pwd)/*/migrations/[0-9]*.py"

#Shapa db env & aliases
export DB_HOSTNAME="localhost"
export DB_USERNAME="postgres"
export DB_PASSWORD="password"

alias shapadb="docker container start shapadb"
alias shapadb-stop="docker container stop shapadb"
alias shapadb-refresh="docker container rm -f shapadb; docker run --name shapadb -p 5432:5432 -v $HOME/DevSquads/shapa/shapa-react-native/src/tests/ui/helpers/database_dumps/:/database_dumps/ -e POSTGRES_PASSWORD=password -d postgres:alpine"
alias shapadb-shell="docker exec -it shapadb bash"
alias shapadb-db-shell="docker exec -it shapadb psql -U postgres"
alias shapa-backend="cd $HOME/DevSquads/shapa/shapa-server/"
alias shapa-frontend="cd $HOME/DevSquads/shapa/shapa-react-native/"
alias shapadb-dumb="cd $HOME/DevSquads/shapa/shapa-server; sh $HOME/DevSquads/shapa/shapa-react-native/src/tests/ui/helpers/database_dumps/update_database_docker.sh; cd -"

#XPay database aliases
alias xpaydb="docker container start xpaydb"
alias xpaydb-stop="docker container stop xpaydb"
alias xpaydb-refresh="docker container rm -f xpaydb; docker run --name xpaydb -p 3306:3306 -e MYSQL_DATABASE=homestead -e MYSQL_USER=homestead -e MYSQL_PASSWORD=secret -e MYSQL_ROOT_PASSWORD=secret -d mysql --default-authentication-plugin=mysql_native_password"
alias xpaydb-shell="docker exec -it xpaydb bash"
alias xpaydb-db-shell="docker exec -it xpaydb mysql -uhomestead -psecret"
alias DevSquads="cd $HOME/DevSquads/"
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#zprof # #Debugging Technique 
```

**Comment by black7375** [comment]
Using too many plugins seems to have caused this problem.
Can you execute `zplugin times`?

P.S. Check this post.
https://htr3n.github.io/2018/07/faster-zsh/

**Comment by MuhmdRaouf** [comment]
@black7375 here's the the output of `zplugin times`

> Plugin loading times:
> 0.048 sec - romkatv/powerlevel10k
> 4.094 sec - robbyrussell/oh-my-zsh
> 0.003 sec - zsh-users/zsh-completions
> 0.045 sec - zsh-users/zsh-autosuggestions
> 0.075 sec - zdharma/fast-syntax-highlighting
> 0.002 sec - https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
> 0.001 sec - OMZ::plugins/adb/_adb
> 0.039 sec - lukechilds/zsh-nvm
> 0.004 sec - zdharma/zsh-diff-so-fancy (command)
> 0.004 sec - zdharma/history-search-multi-word
> 0.005 sec - zsh-users/zsh-history-substring-search
> Total: 4.320 sec

and that's the output of `zplugin report`

> Assuming --all is passed
> Plugin report for romkatv/powerlevel10k
> ---------------------------------------
> Source powerlevel10k.zsh-theme (no reporting)
> Autoload colors with options -U
> Autoload add-zsh-hook with options -U -z
> Autoload powerlevel9k_prepare_prompts
> Autoload powerlevel9k_preexec
> 
> Plugin report for robbyrussell/oh-my-zsh
> ----------------------------------------
> Source git.zsh (no reporting)
> Autoload is-at-least with options -U -z
> Autoload up-line-or-beginning-search with options -U
> Autoload down-line-or-beginning-search with options -U
> Autoload edit-command-line with options -U
> Autoload is-at-least with options -U -z
> Autoload bracketed-paste-magic with options -U -z
> Autoload url-quote-magic with options -U -z
> Saving `compdef _cap bundled_cap=cap' for replay
> Saving `compdef _guard bundled_guard=guard' for replay
> Saving `compdef _kitchen bundled_kitchen=kitchen' for replay
> Saving `compdef _knife bundled_knife=knife' for replay
> Saving `compdef _middleman bundled_middleman=middleman' for replay
> Saving `compdef _nanoc bundled_nanoc=nanoc' for replay
> Saving `compdef _rake bundled_rake=rake' for replay
> Saving `compdef _rspec bundled_rspec=rspec' for replay
> Saving `compdef _spring bundled_spring=spring' for replay
> Saving `compdef _thor bundled_thor=thor' for replay
> Saving `compdef _composer composer' for replay
> Saving `compdef _composer composer.phar' for replay
> Saving `compdef _managepy manage.py' for replay
> Saving `compdef _managepy django' for replay
> Saving `compdef _managepy django-admin' for replay
> Saving `compdef _managepy django-admin.py' for replay
> Saving `compdef _managepy django-manage' for replay
> Autoload add-zsh-hook with options -U
> Autoload source_env
> Saving `compdef _git gcount' for replay
> Saving `compdef _git gdv=git-diff' for replay
> Saving `compdef _grep gfg' for replay
> Saving `compdef _git ggf=git-checkout' for replay
> Saving `compdef _git ggl=git-checkout' for replay
> Saving `compdef _git ggp=git-checkout' for replay
> Saving `compdef _git ggpnp=git-checkout' for replay
> Saving `compdef _git ggu=git-checkout' for replay
> Saving `compdef _git ggpur=git-checkout' for replay
> Saving `compdef _git ggpull=git-checkout' for replay
> Saving `compdef _git ggpush=git-checkout' for replay
> Saving `compdef _git git-svn-dcommit-push=git' for replay
> Saving `compdef _git gk=gitk' for replay
> Saving `compdef _git gke=gitk' for replay
> Saving `compdef _git glp=git-log' for replay
> Saving `compdef _git gpoat=git-push' for replay
> Saving `compdef __go_tool_complete go' for replay
> Saving `compdef _rake rake' for replay
> Saving `compdef _tmux _zsh_tmux_plugin_run' for replay
> 
> Completions:
> _adb [enabled]
> _autopep8 [enabled]
> _boot2docker [enabled]
> _bower [enabled]
> _bundler [enabled]
> _capistrano [enabled]
> _cargo [enabled]
> _celery [enabled]
> _codeclimate [enabled]
> _coffee [enabled]
> _cpanm [enabled]
> _docker-compose [enabled]
> _docker-machine [enabled]
> _docker [enabled]
> _extract [enabled]
> _fab [enabled]
> _gas [enabled]
> _gb [enabled]
> _geeknote [enabled]
> _gem [enabled]
> _git [enabled]
> _hub [enabled]
> _asadmin [enabled]
> _gradle [enabled]
> _gradlew [enabled]
> _jira [enabled]
> _kitchen [enabled]
> _knife [enabled]
> _artisan [enabled]
> _lein [enabled]
> _port [enabled]
> _meteor [enabled]
> _mix [enabled]
> _nanoc [enabled]
> _nomad [enabled]
> _nvm [enabled]
> _pass [enabled]
> _pep8 [enabled]
> _pip [enabled]
> _pod [enabled]
> _powder [enabled]
> _powify [enabled]
> _pylint [enabled]
> _rails [enabled]
> _react-native [enabled]
> _rebar [enabled]
> _redis-cli [enabled]
> _repo [enabled]
> _ros [enabled]
> _rust [enabled]
> _salt [enabled]
> _sbt [enabled]
> _scala [enabled]
> _scw [enabled]
> _spring [enabled]
> _supervisorctl [enabled]
> _supervisord [enabled]
> _swift [enabled]
> _task [enabled]
> _terminitor [enabled]
> _terraform [enabled]
> _theme [enabled]
> _thor [enabled]
> _tmux-cssh [enabled]
> _tmuxinator [enabled]
> _tugboat [enabled]
> _ufw [enabled]
> _vagrant [enabled]
> _vault [enabled]
> _wake [enabled]
> _xcselv [enabled]
> _yarn [enabled]
> _zeus [enabled]
> _n-kill [enabled]
> 
> Plugin report for zsh-users/zsh-completions
> -------------------------------------------
> Source zsh-completions.plugin.zsh (no reporting)
> 
> Completions:
> _afew [enabled]
> _android [enabled]
> _archlinux-java [enabled]
> _artisan [enabled]
> _atach [enabled]
> _bitcoin-cli [enabled]
> _bower [enabled]
> _bundle [enabled]
> _caffeinate [enabled]
> _cap [enabled]
> _cask [enabled]
> _ccache [enabled]
> _cf [enabled]
> _cheat [enabled]
> _choc [enabled]
> _chromium [enabled]
> _cmake [enabled]
> _coffee [enabled]
> _composer [enabled]
> _conan [enabled]
> _console [enabled]
> _dad [enabled]
> _debuild [enabled]
> _dget [enabled]
> _dhcpcd [enabled]
> _diana [enabled]
> _docpad [enabled]
> _drush [enabled]
> _ecdsautil [enabled]
> _emulator [enabled]
> _envdir [enabled]
> _exportfs [enabled]
> _fab [enabled]
> _ffind [enabled]
> _fleetctl [enabled]
> _flutter [enabled]
> _force [enabled]
> _gas [enabled]
> _ghc [enabled]
> _gist [enabled]
> _git-flow [enabled]
> _git-journal [enabled]
> _git-pulls [enabled]
> _git-wtf [enabled]
> _glances [enabled]
> _golang [enabled]
> _google [enabled]
> _gtk-launch [enabled]
> _hledger [enabled]
> _homestead [enabled]
> _httpie [enabled]
> _ibus [enabled]
> _include-what-you-use [enabled]
> _jmeter [enabled]
> _jmeter-plugins [enabled]
> _jonas [enabled]
> _jrnl [enabled]
> _kak [enabled]
> _kitchen [enabled]
> _knife [enabled]
> _language_codes [enabled]
> _lunchy [enabled]
> _middleman [enabled]
> _mina [enabled]
> _mix [enabled]
> _multirust [enabled]
> _mussh [enabled]
> _mvn [enabled]
> _nftables [enabled]
> _node [enabled]
> _nvm [enabled]
> _openssl [enabled]
> _optirun [enabled]
> _patool [enabled]
> _perf [enabled]
> _periscope [enabled]
> _pgsql_utils [enabled]
> _phing [enabled]
> _pixz [enabled]
> _pkcon [enabled]
> _play [enabled]
> _port [enabled]
> _pygmentize [enabled]
> _rails [enabled]
> _ralio [enabled]
> _redis-cli [enabled]
> _rfkill [enabled]
> _rkt [enabled]
> _rslsync [enabled]
> _rspec [enabled]
> _rsvm [enabled]
> _rubocop [enabled]
> _rvm [enabled]
> _sbt [enabled]
> _scala [enabled]
> _scrub [enabled]
> _sdd [enabled]
> _setcap [enabled]
> _sfdx [enabled]
> _showoff [enabled]
> _srm [enabled]
> _stack [enabled]
> _subl [enabled]
> _subliminal [enabled]
> _supervisorctl [enabled]
> _svm [enabled]
> _tarsnap [enabled]
> _teamocil [enabled]
> _thor [enabled]
> _tmuxinator [enabled]
> _tmuxp [enabled]
> _tox [enabled]
> _trash-empty [enabled]
> _trash-list [enabled]
> _trash-put [enabled]
> _trash-restore [enabled]
> _udisksctl [enabled]
> _ufw [enabled]
> _vagrant [enabled]
> _virtualbox [enabled]
> _vnstat [enabled]
> _wemux [enabled]
> _wg-quick [enabled]
> _xinput [enabled]
> _xsel [enabled]
> _yaourt [enabled]
> _yarn [enabled]
> _zcash-cli [enabled]
> 
> Plugin report for zsh-users/zsh-autosuggestions
> -----------------------------------------------
> Source zsh-autosuggestions.plugin.zsh (no reporting)
> Autoload add-zsh-hook with options -U -z
> Autoload _zsh_autosuggest_start
> 
> Plugin report for zdharma/fast-syntax-highlighting
> --------------------------------------------------
> Source fast-syntax-highlighting.plugin.zsh (no reporting)
> Autoload add-zsh-hook with options -U -z
> Autoload _zsh_highlight_preexec_hook
> Autoload is-at-least with options -U -z
> Autoload fast-theme with options -U -z
> Autoload fast-read-ini-file with options -U -z
> Autoload -fast-run-git-command with options -U -z
> Autoload -fast-make-targets with options -U -z
> Autoload -fast-run-command with options -U -z
> Autoload chroma/-git.ch with options -U -z
> Autoload chroma/-hub.ch with options -U -z
> Autoload chroma/-lab.ch with options -U -z
> Autoload chroma/-example.ch with options -U -z
> Autoload chroma/-grep.ch with options -U -z
> Autoload chroma/-perl.ch with options -U -z
> Autoload chroma/-make.ch with options -U -z
> Autoload chroma/-awk.ch with options -U -z
> Autoload chroma/-vim.ch with options -U -z
> Autoload chroma/-source.ch with options -U -z
> Autoload chroma/-sh.ch with options -U -z
> Autoload chroma/-docker.ch with options -U -z
> Autoload chroma/-autoload.ch with options -U -z
> Autoload chroma/-ssh.ch with options -U -z
> Autoload chroma/-scp.ch with options -U -z
> Autoload chroma/-which.ch with options -U -z
> Autoload chroma/-printf.ch with options -U -z
> Autoload chroma/-ruby.ch with options -U -z
> Autoload chroma/-whatis.ch with options -U -z
> Autoload chroma/-alias.ch with options -U -z
> Autoload chroma/-subcommand.ch with options -U -z
> Autoload chroma/-autorandr.ch with options -U -z
> Autoload chroma/-nmcli.ch with options -U -z
> Autoload chroma/-fast-theme.ch with options -U -z
> Autoload chroma/-node.ch with options -U -z
> Autoload chroma/-fpath_peq.ch with options -U -z
> Autoload chroma/-precommand.ch with options -U -z
> Autoload chroma/-subversion.ch with options -U -z
> Autoload chroma/-ionice.ch with options -U -z
> Autoload chroma/-nice.ch with options -U -z
> 
> Completions:
> _fast-theme [enabled]
> 
> Plugin report for lukechilds/zsh-nvm
> ------------------------------------
> Source zsh-nvm.plugin.zsh (no reporting)
> Autoload add-zsh-hook with options -U
> 
> Plugin report for zdharma/zsh-diff-so-fancy
> -------------------------------------------
> /Users/snowflake/.zplugin/plugins/zdharma---zsh-diff-so-fancy/bin added to $PATH
> 
> Plugin report for zdharma/history-search-multi-word
> ---------------------------------------------------
> Source history-search-multi-word.plugin.zsh (no reporting)
> Autoload history-search-multi-word
> Autoload hsmw-context-main
> 
> Plugin report for zsh-users/zsh-history-substring-search
> --------------------------------------------------------
> Source zsh-history-substring-search.plugin.zsh (no reporting)

**Comment by black7375** [comment]
It looks like a bottleneck here.
> 4.094 sec - robbyrussell/oh-my-zsh

This is my configuration, and we can see that some plugins are consuming a lot of time.
```
0.010 sec - OMZ::plugins/autojump/autojump.plugin.zsh
0.688 sec - OMZ::plugins/command-not-found/command-not-found.plugin.zsh
0.649 sec - OMZ::plugins/fzf/fzf.plugin.zsh
0.002 sec - OMZ::plugins/git/git.plugin.zsh
0.001 sec - OMZ::plugins/pip/pip.plugin.zsh
0.001 sec - OMZ::plugins/sudo/sudo.plugin.zsh
0.128 sec - OMZ::plugins/thefuck/thefuck.plugin.zsh
0.001 sec - OMZ::plugins/tmux/tmux.plugin.zsh
0.001 sec - OMZ::plugins/tmuxinator/tmuxinator.plugin.zsh
0.002 sec - OMZ::plugins/urltools/urltools.plugin.zsh
```
I think consider disabling or configuring to  autoload such plugins.

**Comment by laggardkernel** [comment]
You should **do things in the zplugin way**. Just use `ice svn` to load only the plugins you need from`robbyrussell/oh-my-zsh`. e.g.

```bash
zplugin ice svn
zplugin snippet OMZ::plugins/urltools
```

**Comment by MuhmdRaouf** [comment]
> I'm in a hospital right now, but it seems that the bottle neck is the Oh My Zsh loading way

@psprint are you okie man, hope everything is good, never mind about my prompt now it can wait i used to use swiss knife tool now i sm running both OMZ slong side Zplugin , make sure you are okie first then you can help me out later i can wait its totally okie.

**Comment by MuhmdRaouf** [comment]
Hey, hope you're fine now buddy, so i have found why my prompet is freezing.
the prompet freeze cut of the loading of OMZ, here's the snippet
```
# Path to your oh-my-zsh installation.
ZSH="$HOME/.zplugin/plugins/robbyrussell---oh-my-zsh/"

# OMZ things to source
local _ZSHRC_OMZ_SRCS=(
  # Libs
  lib/compfix.zsh
  lib/completion.zsh
  lib/functions.zsh
  lib/diagnostics.zsh
  lib/grep.zsh
  lib/key-bindings.zsh
  lib/misc.zsh
  lib/spectrum.zsh
  lib/termsupport.zsh

  # Plugins
  plugins/bundler/bundler.plugin.zsh
  plugins/colored-man-pages/colored-man-pages.plugin.zsh
  plugins/command-not-found/command-not-found.plugin.zsh
  plugins/composer/composer.plugin.zsh
  plugins/django/django.plugin.zsh
  plugins/docker-compose/docker-compose.plugin.zsh
  plugins/docker-machine/docker-machine.plugin.zsh
  plugins/dotenv/dotenv.plugin.zsh
  plugins/git-auto-fetch/git-auto-fetch.plugin.zsh
  plugins/git/git.plugin.zsh
  plugins/golang/golang.plugin.zsh
  plugins/jenv/jenv.plugin.zsh
  plugins/npm/npm.plugin.zsh
  plugins/rake-fast/rake-fast.plugin.zsh
  plugins/rbenv/rbenv.plugin.zsh
  plugins/react-native/react-native.plugin.zsh
)

zplugin ice wait"0" from"gh" pick"/dev/null" nocompletions blockf lucid \
    multisrc"${_ZSHRC_OMZ_SRCS}" compile"${(j.|.)_ZSHRC_OMZ_SRCS}"
zplugin load robbyrussell/oh-my-zsh
```

my prompet wait till it finishes loading all this plugins and libs.
the first workaround is it to load each lib and plugin on its own, but why to do so while i am having multisrc tool, so is there's something i can do ?

**Comment by psprint** [comment]
I'm looking into this, to see if it is possible to automatically break up the `multisrc''` ice so that it feeds CPU time to the prompt.
