### ISSUE TITLE
Need help with pyenv management

### ISSUE THREAD

**Issue by pythoninja** [zdharma/zinit#142]
I am trying to manage pyenv with these commands:
```
zplugin ice atclone"./libexec/pyenv init - > zpyenv.zsh" atinit"export PYENV_ROOT=\"$ZPLGM[PLUGINS_DIR]/pyenv---pyenv/bin\" && export PATH=\"$ZPLGM[PLUGINS_DIR]/pyenv---pyenv/bin:$PATH\"" atpull"%atclone" pick"zpyenv.zsh" nocompile"!"
zplugin light pyenv/pyenv
```

It works well before I am trying to `pyenv install --list` and then I got error message:
```
mnj$ ~ pyenv install
pyenv: no such command `install'
```

I am not sure about how to correctly manage $PATH or maybe I am trying to use zplugin wrongly and solve trouble for which this tool wasn't created?

**Comment by psprint** [comment]
I'm pretty tired currently but looking at `pyenv --help` (after running your snippet) reveals there's indeed no `install` command for `pyenv`.

**Comment by pythoninja** [comment]
Yeah, here is a main problem. Something went wrong with installation process.
This is old issue about why `install` command is missing pyenv/pyenv#777

Btw, old-school `pyenv` installation is working as expected.

**Comment by pythoninja** [comment]
@psprint do you have any suggestions?

**Comment by psprint** [comment]
I can only hint how to shorten the atinit hook:

```zsh
zplugin ice atclone"./libexec/pyenv init - > zpyenv.zsh" atinit"export PYENV_ROOT=\"$ZPLGM[PLUGINS_DIR]/pyenv---pyenv/bin\" && export PATH=\"\$PWD/bin:$PATH\"" atpull"%atclone" pick"zpyenv.zsh" nocompile"!"
zplugin light pyenv/pyenv
```

I cannot help with the installation of pyenv.

**Comment by pythoninja** [comment]
Nice, thank you, thank you for your help! It makes me easy to understand your tool.

**Comment by psprint** [comment]
Glad that I could help. Thank you **very much** for the donation!

**Comment by hhpsv** [comment]
@psprint hi again, I just noticed that Pyenv was broken...
I take snipped from your [Gallery](https://zdharma.org/zinit/wiki/GALLERY/)

```
zinit ice atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init - > zpyenv.zsh' \
    atinit'export PYENV_ROOT="$PWD"' atpull"%atclone" \
    as'command' pick'bin/pyenv' src"zpyenv.zsh" nocompile'!'
zinit light pyenv/pyenv
```

And it doesn't work on my end. Could you help me please with that? I can't figure out where is the problem.

```
$ which python
/usr/bin/python

$ eval "$(pyenv init -)"
$ which python
/home/psv/.zinit/plugins/pyenv---pyenv/shims/python
```

**Comment by pythoninja** [comment]
@psprint hi again, I just noticed that Pyenv was broken...
I take snipped from your [Gallery](https://zdharma.org/zinit/wiki/GALLERY/)

```
zinit ice atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init - > zpyenv.zsh' \
    atinit'export PYENV_ROOT="$PWD"' atpull"%atclone" \
    as'command' pick'bin/pyenv' src"zpyenv.zsh" nocompile'!'
zinit light pyenv/pyenv
```

And it doesn't work on my end. Could you help me please with that? I can't figure out where is the problem.

```
$ which python
/usr/bin/python

$ eval "$(pyenv init -)"
$ which python
/home/psv/.zinit/plugins/pyenv---pyenv/shims/python
```

**Comment by psprint** [comment]
Doesn't the output of the command indicate that it worked fine? Also, there's [pyenv](https://github.com/Zsh-Packages/pyenv) package.

**Comment by pythoninja** [comment]
> Doesn't the output of the command indicate that it worked fine? Also, there's [pyenv](https://github.com/Zsh-Packages/pyenv) package.

No, it doesn't work at all because `which python` points to system python binary but should point to shims `/home/psv/.zinit/plugins/pyenv---pyenv/shims/python`

**Comment by pythoninja** [comment]
Don't know how but with [pyenv package](https://github.com/Zsh-Packages/pyenv) it works fine. Thank you!

**Comment by tony** [comment]
@pythoninja What does the zinit look like for https://github.com/Zsh-Packages/pyenv?

**Comment by pschmitt** [comment]
```
zinit pack ​for​ pyenv
```

**Comment by pythoninja** [comment]
@tony I do not understand your question

**Comment by tony** [comment]
@pythoninja sorry for the misunderstanding.  I was asking for what zinit command you ended up using to load pyenv.

I ended up using what @pschmitt gave for now
