### ISSUE TITLE
Feature request: Download binarys from arbitrary URLs

### ISSUE THREAD

**Issue by lhernanz** [zdharma/zinit#183]
**Is your feature request related to a problem? Please describe.**
Not all the binaries that I want to use are hosted in github or similar sites. Some of them are distributed via other web pages. I would love to be able to use zplugin to download and managed them as the needed functionality is really similar as the one already included in zplugin (unpack zip file, rename binary, etc.). 

One random example could be some of the aws tools, whose recommend installation command is: `sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest`

**Describe the solution you'd like**
I would love to be able to execute something like 
```
zplugin ice from"amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest" as"program" mv"ecs-cli* -> ecs-cli"
zplugin load ecs-cli
```
Some other programs are trickier. For example, terraform offers their own release page with a dir per version (see `https://releases.hashicorp.com/terraform`). Here, it would be ideal if zplugin could identify the latest version and download it, but I understand that the complexity would be higher as different web pages could have different naming schemes, url patterns, etc.

```
zplugin ice from"releases.hashicorp.com/terraform" as"program" ver"latest"
zplugin load terraform/terraform
```

**Describe alternatives you've considered**
I have been unable to make this to work in zplugin and I am not aware of any alternative that could provide similar functionality. You could argue that the above mentioned programs do not have anything to do with ZSH but, on one hand, they are provided as examples only and, on the other, they could be part of a fully configured zsh session.

**Comment by psprint** [comment]
The first case is achievable by:

```zsh
zplugin ice mv'*latest -> ecs-cli' pick'ecs-cli' as"command"
zplugin snippet https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
```

or with use of `zplugin/z-a-bin-gem-node' annex:

```zsh
zplugin ice mv'*latest -> ecs-cli' atclone'chmod +x *' atpull'%atclone' pick'/dev/null' sbin"ecs-cli"
zplugin snippet https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
```

which doesn't add anything to the PATH. See also #177 

I'll think about adding a feature for this. It'll most probably be done through an annex.

**Comment by lhernanz** [comment]
Amazing! It works for the first case!

I would suggest that you would consider renaming the snippet command to something more straightforward for the future (download?). There is a lot of magic that you can do with zplugin but some of them is not evident at all.

**Comment by psprint** [comment]
Yes, that's an interesting idea, I might add `download` and/or `dl` aliases for the `snippet` subcommand.

**Comment by psprint** [comment]
Hi!
I would like to share that there's [ecs-cli package](https://github.com/Zsh-Packages/ecs-cli] for the recent new package support added to Zplugin. It's sufficient to issue `zplugin pack for ecs-cli` to have the tool installed.

**Comment by psprint** [comment]
Also, I've created an annex that allows to extract URLs from download pages and download them: [zplugin/z-a-as-track](https://github.com/zplugin/z-a-as-track). However, it isn't capable of downloading the `terraform` files, because the web-page lists *directories* / *sub-pages* on which the URLs are located. I'm thinking about a possible solution to this.

**Comment by psprint** [comment]
The issue with two-stage download pages has been solved – by adding a `dlink0''` ice. For the terraform, it works as follows:

```zsh
zplugin id-as'terraform' atclone'zpextract terraform zip' as'track|command' \
    dlink0'/terraform/%VERSION%/' \
    dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_386.zip' for \
        http://releases.hashicorp.com/terraform/
```

Or, with use of the bin-gem-node annex to not alter `$PATH`:

```zsh
zplugin id-as'terraform' atclone'zpextract terraform zip' as'track|null' sbin \
    dlink0'/terraform/%VERSION%/' \
    dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_386.zip' for \
        http://releases.hashicorp.com/terraform/
```

**Comment by lhernanz** [comment]
Amazing, thanks you very much!

I can confirm that the snippet version works:

```
$ zplugin id-as=terraform atclone='zpextract terraform zip' as='monitor|command' \
  atpull='%atclone' dlink0='/terraform/%VERSION%/' \
  dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_amd64.zip'
$ zplugin snippet 'https://releases.hashicorp.com/terraform'

as-monitor annex: Matched the following URL: https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip

Setting up snippet           terraform... (as terraform)
Downloading `terraform' (with curl, wget, lftp)...
ziextract: Unpacking the files from: `terraform'...
Archive:  terraform
  inflating: terraform               
ziextract: Successfully extracted and assigned +x chmod to the file: `terraform'.
```
But the single line version does not
```
$ zplugin id-as=terraform atclone='zpextract terraform zip' as='monitor|command' \
    atpull='%atclone' dlink0='/terraform/%VERSION%/' \
    dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_amd64.zip' for https://releases.hashicorp.com/terraform/
as-monitor annex: ERROR: as'monitor|command' ice can be used only with snippets
as-monitor annex: ERROR: as'monitor|command' ice can be used only with snippets
as-monitor annex: ERROR: as'monitor|command' ice can be used only with snippets

Downloading https://releases.hashicorp.com/terraform... (as terraform...)

Cloning into '/home/cb-aws/.zplugin/plugins/terraform'...
remote: Not Found
fatal: repository 'https://github.com/https://releases.hashicorp.com/terraform/' not found
```
Notice the weird URL in the last line.

**Comment by psprint** [comment]
The exact same code works for me. Could you do `self-update`, maybe it'll help?

**Comment by lhernanz** [comment]
I am running the latest version. But, as you say, the `is-snippet` made the trick. It is working now.
Thanks!

**Comment by psprint** [comment]
Ok, that's fine. Thanks.

**Comment by mcanevet** [comment]
When trying with 
```
zinit id-as'terraform' as'monitor|command' atclone'zpextract terraform zip' atpull'%atclone' \
    dlink0'/terraform/%VERSION%/' \
    dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_amd64.zip' is-snippet for \
        https://releases.hashicorp.com/terraform
```
I get :
```
as-monitor annex: ERROR: couldn't match the URL at the download page (which is https://releases.hashicorp.com/terraform; the snippet is being identified as             terraform; was matching https://releases.hashicorp.com/terraform/https://releases.hashicorp.com/terraform).
```
Any clue?

**Comment by alephnull** [comment]
```
% zi id-as'terraform' as'monitor|command' atclone'zpextract terraform zip' atpull'%atclone' \
    dlink0'/terraform/%VERSION%/' \
    dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_amd64.zip' is-snippet for \
        https://releases.hashicorp.com/terraform
ERROR: Unknown subcommand: `dlink0/terraform/ERSION/home/alok' (it should be one of, e.g.: `load', `snippet', `update', `delete', ..., e.g.: `zinit load username/reponame') or a for-based command body (i.e.: e.g.: `zinit ...ice-spec... for ...plugin or snippet ID-1 ID-2 ... ...'). See `help' for more usage information and the complete list of the subcommands.
```

Here, the `/home/alok` is my homedir. This broke recently, I think.

**Comment by hrai** [comment]
> ```
> % zi id-as'terraform' as'monitor|command' atclone'zpextract terraform zip' atpull'%atclone' \
>     dlink0'/terraform/%VERSION%/' \
>     dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_amd64.zip' is-snippet for \
>         https://releases.hashicorp.com/terraform
> ERROR: Unknown subcommand: `dlink0/terraform/ERSION/home/alok' (it should be one of, e.g.: `load', `snippet', `update', `delete', ..., e.g.: `zinit load username/reponame') or a for-based command body (i.e.: e.g.: `zinit ...ice-spec... for ...plugin or snippet ID-1 ID-2 ... ...'). See `help' for more usage information and the complete list of the subcommands.
> ```
> 
> Here, the `/home/alok` is my homedir. This broke recently, I think.

I get similar error. 

![image](https://user-images.githubusercontent.com/4055444/94358705-4846a700-00e6-11eb-879c-daa30dac644d.png)

**Comment by alephnull** [comment]
There's a PR that restores the deleted code at https://github.com/zinit-zsh/z-a-readurl/pull/5

**Comment by mcouthon** [comment]
When I got the `dlink0/terraform/VERSION` error it was because I didn't think about actually loading the annex with `zinit light zinit-zsh/z-a-readurl`. After this, the code worked on macOS with:

```bash
zinit id-as'terraform' as'readurl|command' extract \
    dlink0'/terraform/%VERSION%/~%.*-(alpha|beta|rc).*%' \
    dlink'/terraform/%VERSION%/terraform_%VERSION%_darwin_amd64.zip' \
    for https://releases.hashicorp.com/terraform/
```
(I'm filtering out the non-stable versions here).
