### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by rafacortese** [zdharma/zinit#2]
Downloading zinit-zsh/z-a-as-monitor... (as zinit-zsh/z-a-as-monitor...)

Cloning into '/Users/Leonardo/.zinit/plugins/zinit-zsh---z-a-as-monitor'...
Username for 'https://github.com': rafacortese
Password for 'https://rafacortese@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/zinit-zsh/z-a-as-monitor/' not found

Clone failed (code: 128).

Downloading zinit-zsh/z-a-bin-gem-node... (as zinit-zsh/z-a-bin-gem-node...)

Cloning into '/Users/Leonardo/.zinit/plugins/zinit-zsh---z-a-bin-gem-node'...
Username for 'https://github.com': rafacortese
Password for 'https://rafacortese@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/zinit-zsh/z-a-bin-gem-node/' not found

Clone failed (code: 128).

**Comment by gibfahn** [comment]
Dup of https://github.com/zdharma/zinit/issues/1
