### ISSUE TITLE
Feature request: allow to skip extraction for binary releases

### ISSUE THREAD

**Issue by Gerrit-K** [zdharma/zinit#230]
**Is your feature request related to a problem? Please describe.**
I want to use binary releases of programs that are not packed into gzipped tarballs (e.g. [stedolan/jq](https://github.com/stedolan/jq/releases)). However, using `from'gh-r'`, zplugin always tries to extract whatever it finds. If it doesn't find an archive it just skips extraction:
```
zpextract: WARNING: didn't recognize the archive type (no extraction has been done).
zpextract: Successfully extracted and assigned +x chmod to the file: `jq-linux-x86_64'.
```
The downside here is that the version somehow isn't remembered. So subsequent calls to `zpl update` force a complete download again (in this case "only" a ~6s delay, but there are much larger binaries around):
![image](https://user-images.githubusercontent.com/8766565/71295576-c10d1b80-237c-11ea-9f65-59e5dba6a191.png)

**Describe the solution you'd like**
A simple ice, e.g. `noextract`, to prevent zplugin from extracting github releases

**Describe alternatives you've considered**
I just read about `z-a-as-track` (in #183, which might be related, kind of ...) and believe it could solve this issue to some degree, but then I would probably lose the comfort of automatic arch detection again.

**Comment by psprint** [comment]
Thanks for bringing this up. It is done – with a slight modification: the warning will be skipped when no binaries will be found upon the download. This way the binary still gets a guaranteed `+x`.
