### ISSUE TITLE
bad math expression: illegal character: {

### ISSUE THREAD

**Issue by conao3** [zdharma/zinit#231]
**Describe the bug**
I want to install zplugin and do below steps.
And see an error.

**To Reproduce**
Steps to reproduce the behavior.

- sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
- change `$HOME/.zshrc`
```
conao-manjaro-selene% cat -n .zshrc 
     1	### Added by Zplugin's installer
     2	source "$HOME/.zplugin/bin/zplugin.zsh"
     3	autoload -Uz _zplugin
     4	(( \${+_comps} )) && _comps[zplugin]=_zplugin
     5	### End of Zplugin installer's chunk
```
- run zsh and see error
```
$ echo $0
bash

$ zsh
/home/conao/.zshrc:4: bad math expression: illegal character: {
conao-manjaro-selene% echo $0
zsh
```

**Expected behavior**
Initialize zplugin with no errors

**Screenshots**
![Screenshot_2019-12-22_15-28-23](https://user-images.githubusercontent.com/4703128/71318121-d8a8e900-24cf-11ea-92ee-aa19573ba2d5.png)

**Versions:**
 - $ZSH_VERSION ==
   - 5.7.1
 - Operating system name and version (uname -a):
   - Linux conao-manjaro-selene 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64 GNU/Linux

**Additional context**
None

**Comment by psprint** [comment]
Could you show `sh --version` (or some other option that shows version)? Because the installer's code is correct, it shouldn't output such code to the `zshrc`. You can also fix the `zshrc` by removing the backslash from before `${+_comps}`.
