### ISSUE TITLE
`zinit ice wait"1" lucid atload'PluginFinish'` can't work

### ISSUE THREAD

**Issue by fcying** [zdharma/zinit#244]
**Describe the bug**
update to the last version 
`zinit ice wait"1" lucid atload'PluginFinish'` can't work.

**To Reproduce**
```
function PluginFinish() {
    echo "aaa"
}
zinit ice wait"1" lucid atload'PluginFinish'
```

**Expected behavior**
work fine.

**Versions:**
$ZSH_VERSION  5.7.1
Linux gateway 5.3.0-0.bpo.2-cloud-amd64 #1 SMP Debian 5.3.9-2~bpo10+1 (2019-11-13) x86_64 GNU/Linux
zinit: aef3c9107ed4220355e462bdd2db334f5f54cd13

**Comment by psprint** [comment]
It will work as soon as you load any plugin, i.e.:

```zsh
function PluginFinish() {
    echo "aaa"
}
zinit ice wait"1" lucid atload'PluginFinish'
zplugin load zdharma/null
```
