### ISSUE TITLE
Request: Zinit named 3.X versions using semantic versioning

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zinit#246]
I assume that when the Zinit name transition is complete there'll be a major version bump.

From then on, could semantic versioning be used instead of the current string sorting versions? I think it would make packaging play a lot nicer since most systems I know of expect semantic version numbering. (Personally it would make deb packaging easier for me.)

( https://github.com/zdharma/zinit/releases shows 2.12 as older than 2.2 for example )

**Comment by psprint** [comment]
Is the semantic versioning only about using the 3 components? Because `is-at-least` doesn't yield 2.12 as older than 2.2:

```
 is-at-least 2.12 2.2 && print 1 || print 0
0
```

**Comment by romkatv** [comment]
It's a de facto standard convention that version `12.0` goes after `2.0` (because 12 is greater than 2). Likewise, version `0.12` goes after `0.2` (same reason).

**Comment by psprint** [comment]
Ah, I think I see what you mean… I've did some weird versioning, with "05", "06", etc. and then "12" after "1" and before "2". Thanks for pointing this out!

**Comment by psprint** [comment]
The rename is fairly complete, what's left is only the wiki and sister projects, so I've tagged the version 3.0.
