### ISSUE TITLE
ZPLGM: assignment to invalid subscript range

### ISSUE THREAD

**Issue by laggardkernel** [zdharma/zinit#248]
**Describe the bug**
```
ZPLGM: assignment to invalid subscript range
```

It seems caused by the renaming. The old option `ZPLGM` is gone?

Related lines in my zsh conf.

```shell
_custom_compinit() {
  # borrowed from prezto
  local _comp_files=(${ZPLGM[ZCOMPDUMP_PATH]:-${ZDOTDIR:-$HOME}/.zcompdump}(Nm-20))
  if (( $#_comp_files )); then
    ZPLGM[COMPINIT_OPTS]="-i -C"
  else
    ZPLGM[COMPINIT_OPTS]="-i"
  fi
}
```

**Versions:**
 - $ZSH_VERSION == zsh 5.7.1 (x86_64-pc-linux-gnu)

-----

BTW, the OMZ and Prezto modules don't get installed during setting up my new computer.

Related lines

```shell
zstyle ':prezto:environment:termcap' color "no"
zplugin ice svn
zplugin snippet PZT::modules/environment
```

But after I reset the zplugin to an old version `git reset --hard a80e2a58d8c`, everything works well.

**Comment by psprint** [comment]
The `ZPLGM` is renamed to `ZINIT`. There is a compatibility code at the beginning of `zinit.zsh`:

```zsh
typeset -gAH ZPLGM
ZINIT=( "${(kv)ZPLGM[@]}" "${(kv)ZINIT[@]}" )
unset ZPLGM
```

however, as it can be seen it unsets the `ZPLGM` to not pollute the namespace and to not produce silent errors of the parameter being ignored.

As for the snippet issue, I've ran the code and it did install the `environment` module. Could I ask you to do a little investigation of why it's not installing to you?

**Comment by Alkindi42** [comment]
Hello,

I had the same issue about "ZPLGM: assignment to invalid subscript range". I just renamed **ZPLGM** by **ZINIT** in my configuration file and it works.

**Comment by psprint** [comment]
I've also tested a `ZDOTDIR=$PWD zsh -i` with a config that contains the commands and observed no problems. @laggardkernel, apparently only you can help..

**Comment by laggardkernel** [comment]
Thanks for your help. The problem is that `ZPLGM[COMPINIT_OPTS]` is set after the plugin manger is initialized, at which time the `ZPLGM` is unset.

The `PZT::modules/environment` may just be interrupted last time. I haven't figured the problem out yet.

**Comment by laggardkernel** [comment]
It turns out the `ZPLGM` is set in turbo mode, which may be the cause.
