### ISSUE TITLE
zplugin's installer added commands to .zshrc file erroring now after update to zinit when sourcing .zshrc

### ISSUE THREAD

**Issue by leeallen337** [zdharma/zinit#252]
**Describe the bug**
I installed `zplugin` before the name change and it added the following to my `.zshrc`

```
### Added by Zplugin's installer
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin installer's chunk
```

I just did a `zplugin self-update` followed by a `zinit update --all` per the changelog. 

Now when I do a `source ~/.zshrc` I get the following error

```
compinit:503: no such file or directory: /Users/<my computer name>/.zplugin/completions/_zplugin
```

**To Reproduce**
- Installed before the name change
- Do a `zplugin self-update`
- Source `.zshrc`

**Expected behavior**
- No error message

**Versions:**
zsh 5.7.1 (x86_64-apple-darwin19.0)

**Additional context**
- At the bottom of my `.zshrc` file I have the following
```
fpath=(~/.zsh/functions $fpath)
autoload -Uz compinit
compinit -u
```
To add completions based on [this stack exchange](https://unix.stackexchange.com/a/496760)

- I've also updated everywhere else from `zplugin` to `zinit`

**Comment by psprint** [comment]
If you run `zinit compinnit` the error will go away.

**Comment by leeallen337** [comment]
This worked! Thanks!
