### ISSUE TITLE
For syntax does not work with github releases

### ISSUE THREAD

**Issue by jjzmajic** [zdharma/zinit#257]
**Describe the bug**
For syntax does not work with github releases

**To Reproduce**
```sh
zinit silent wait light-mode from:gh-r as:program for \
      mv:'bat-**/bat -> bat' sharkdp/bat \
      mv:'exa-* -> exa' ogham/exa
```
Doesn't work, but
```sh
zinit ice silent wait light-mode from:gh-r as:program mv:'bat-**/bat -> bat' && zinit light sharkdp/bat
<same for exa>
```
does.

**Expected behavior**
Both should work the same

**Versions:**
 - $ZSH_VERSION == zsh 5.7.1 (x86_64-unknown-linux-gnu)
 - Operating system name and version (uname -a): Linux void 5.4.13_2 #⁠1 SMP PREEMPT Sun Jan 19 12:22:44 UTC 2020 x86_64 GNU/Linux

**Comment by psprint** [comment]
The problem is the `sh` ice which is in conflict with `sharkdp`. To resolve it, use the `@` prefix, i.e.: `@sharkdp`.

**Comment by jjzmajic** [comment]
It works! Thanks! I could have sworn I tried that. Must have been other issues with my config at the time.
