### ISSUE TITLE
Ice no longer working

### ISSUE THREAD

**Issue by jamescodesthings** [zdharma/zinit#259]
**Describe the bug**
Adding ice or wait commands stops a plugin from loading for me

**To Reproduce**
```
zinit ice wait'0a' lucid
zinit load djui/alias-tips
```

then `zinit list`, the plugin was not loaded for me

**Expected behavior**
The plugin should load

**Screenshots**
![image](https://user-images.githubusercontent.com/32203362/73136219-2242a180-4043-11ea-98d1-89527aef0d7d.png)

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): `Darwin Jamess-MBP.fritz.box 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

**Additional context**
Reinstalled zplugin after a system restore. Had to update my scripts to deal with the rename.
Removing all ice wait commands from before plugin load makes plugins load, but some require an ice command. e.g. doing
```
zinit ice wait blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions
```
does not load the zsh-completions plugin.

Here's my scripts, because they're a bit intense:

the .zshrc is symlinked into $HOME. Then it loads zinit, and loads the plugins.zsh file.

In the plugins.zsh file I've found that replacing the top line with the suggested zsh-completions commands leads to the plugin not being loaded (checked with zinit list)

https://drive.google.com/open?id=1kYgUFai7Dy_99f4c1ug6CMgM0hOw84Rw

**Comment by psprint** [comment]
Thanks for the report. The bug is really weird, as for me the command works. Could you try to enter the command in the shell and see if the plugin loads? The `custom.zsh` contains only a symlink to the directory in `$HOME`, not the actual directory.

**Comment by jamescodesthings** [comment]
It is an odd one. I've tried a few things and it seems any ice modifier causes the plugin not to load.

My original attempts were

```
zinit ice wait'0a' lucid
zinit [plugin]
```

to async load a bunch of things that aren't needed immediately.

Trying the commands in shell seem to work, zsh-completions shows up with a green asterix when I run zinit list. (See below)

![image](https://user-images.githubusercontent.com/32203362/73169747-ac970e00-40f4-11ea-8443-d6c06e13d0e8.png)

whoops, that's my bad. Here it is again, I'm using macup to symlink dotfiles and custom scripts into home. This one should contain the scripts:

https://drive.google.com/open?id=1sxRuZk2zie6X4YL42AfN_vdzREO-AytX

As a loose overview .zshrc is symlinked into $HOME as well, so it's the main rc file.

That goes through a bunch of initialisation scripts: functions, things used elsewhere in the scripts, then zinit and finally `plugins.zsh` which runs the zinit commands.

The zinit commands work without modifiers, but then adding `zinit ice wait '0a'` with its various other modifiers leads to a plugin not loading.

I came across this because I was restoring from scratch, and after the restore I found that zinit's name had changed, leading me to have to update the `plugins.zsh` file. Once I'd updated by replacing zplugin with zinit I found that only plugins without ice commands before them were being loaded. Removing them then made the plugins load but the whole reason I was using zinit was to improve performance over oh-my-zsh (ms to load rather than seconds).

I also used to have some functions in the functions directory which were shorthands for loading plugins but I refactored them out into inline commands when things stopped working.

Any help would be appreciated.

**Comment by jamescodesthings** [comment]
Interestingly enough I've now also found that running `source ~/.custom/plugins.zsh` in the terminal after it has loaded also loads the plugins 😕 

The example I've used here is `alias-tips` which is async loaded... On opening the shell it has not loaded, running `source ~/.custom/plugins.zsh` leads to alias-tips being loaded... but only in the shell, I've checked with echo statements that the file is the same file being run both times... I'm really confused now.

**Comment by jamescodesthings** [comment]
Adding `echo '~/.custom/plugins.zsh run'` to the plugins.zsh file lead to this odd session...

![image](https://user-images.githubusercontent.com/32203362/73170505-81adb980-40f6-11ea-8c65-d447fdc68689.png)

**Comment by jamescodesthings** [comment]
🤦‍♂ Caught it, checked `.zshrc` and found:

```
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p $HOME/.zinit
    command git clone https://github.com/zdharma/zinit $HOME/.zinit/bin && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f" || \
        print -P "%F{160}▓▒░ The clone has failed.%f"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit installer's chunk```

Which would I guess reload things after `plugins.zsh` has run 🤦‍♂ Thanks for the help!

**Comment by jamescodesthings** [comment]
For anyone who comes here in the future here's what I've ended up with:

[fixed.zip](https://github.com/zdharma/zinit/files/4117070/fixed.zip)

Startup time is now smooth and everything I wanted working is working. Function to work with zinit is `zload` and it's damn cool.

**Comment by psprint** [comment]
Great that it resolved. I've also updated the installer so that it checks for `zplugin.zsh`, not only `zinit.zsh`, before updating zshrc.
