### ISSUE TITLE
CentOS 6.10 (zsh 4.3.11) parse error zinit

### ISSUE THREAD

**Issue by 53JIlLenWe11** [zdharma/zinit#262]
**Describe the bug**
I am trying to run Zinit on a CentOS 6.10 (zsh 4.3.11).
Any attempt to load zsh, even from a shell with it only loading zinit.zsh, I get:
```
/home/user/.zinit/bin/zinit.zsh:838: parse error near `"$@"' 
/home/user/.zshrc:40: command not found: zinit               
/home/user/.zshrc:40: command not found: zinit               
   *
   *
   *
```

**Versions:**
 - ZSH Version = 4.3.11
 - Operating system name and version : CentOS 6.10

**Comment by psprint** [comment]
4.3.11 is a very old Zsh version. It doesn't support passing arguments to the anonymous functions, a feature that's used in 5r places in Zinit. I'd rather not simulate the argument passing, as something else will probably not work anywy.

**Comment by atwok** [comment]
Hi fellow corporate worker stuck on a "stable" server version of linux!  :)

https://docs.conda.io/en/latest/miniconda.html

This is the only "package" installer I've found that I can use as a user to update my own environment.

There is a 5.6.2 version of zsh in the conda-forge repository.  Good luck!

**Comment by psprint** [comment]
I also suggest to build Zsh from source. What's only needed is this:

```
git clone --depth=1 https://github.com/zsh-users/zsh my-zsh
cd my-zsh
./.preconfig
./configure
make
make install
```

**Comment by 53JIlLenWe11** [comment]
thanks!
