### ISSUE TITLE
"Couldn't compile" PZT directory and editor snippets

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/zinit#263]
I get the following with `zinit snippet PZT::modules/directory/init.zsh` and `zinit snippet PZT::modules/editor/init.zsh`:

```
Couldn't compile `init.zsh', it MIGHT be wrongly downloaded
(snippet URL points to a directory instead of a file?
to download directory, use preceding: zinit ice svn).
```

If I do `zcompile init.zsh` on these snippets manually, I don't get any errors. What could be the problem?

**Comment by marlonrichert** [comment]
It seems to work fine when I add `zinit ice nocompile`, but why do I need to add that in the first place?

**Comment by psprint** [comment]
Prezto modules utilize `SHORT_LOOPS` option, so I've removed disabling of it in the function that invokes `zcompile` and now there shouldn't be any problem.
