### ISSUE TITLE
Request: Add a cheatsheet of ice modifiers

### ISSUE THREAD

**Issue by Brettm12345** [zdharma/zinit#264]
It would be really helpful to have a cheatsheet of ice modifiers in the documentation and a command displaying them. I always forget things like if it's `atinit` or `oninit` and it would be really helpful knowing exactly what everything did

**Comment by psprint** [comment]
That's a nice idea, thanks!

niedz., 16 lut 2020, 08:45 użytkownik Brett Mandler <
notifications@github.com> napisał:
