### ISSUE TITLE
Unable to use bindkeys for certain keycodes

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#271]
**Describe the bug**
The ice `bindmap'\e[1;6D -> ^[[1;5A; \e[1;6C -> ^[[1;5B'` does not correctly rebind the keys as expected. It simply leaves them untouched. 

**To Reproduce**
Loading the following plugin:
```zsh
zinit wait light-mode trackbinds bindmap'\e[1;6D -> ^[[1;5A; \e[1;6C -> ^[[1;5B' \
pick'dircycle.zsh' for michaelxmcbride/zsh-dircycle
```
Running `zinit report michaelxmcbride/zsh-dircycle` shows the keys have not been rebound.

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Linux Nicks-Laptop 5.4.0-17.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.4-23.2~bullseye (2020-02-01) x86_64 GNU/Linux`

**Additional context**
In another plugin, I was able to use the following successfully: `bindmap'\e\e -> ^[OP^[OP'` and can do the same for this plugin with some editing, it seems the specific keybinds listed at the beginning cause issues.

**Comment by psprint** [comment]
I've fixed the bug. The following works:

```zsh
zinit wait light-mode trackbinds bindmap'"\\e[1\;6D" -> \\e[1\;5A; \\e[1\;6C -> ^[[1\;5B' \ 
pick'dircycle.zsh' for michaelxmcbride/zsh-dircycle
```

The internal semicolons now need to be quoted with a backslash.

**Comment by NICHOLAS85** [comment]
Thanks, works correctly now!
