### ISSUE TITLE
Plugins loaded after snippet in for-syntax fail to load

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#272]
**Describe the bug**
As of 985c57f, using the for-syntax, non-snippet plugins loaded after snippets are loaded as snippets, which fails.

**To Reproduce**
Load a series of plugins using the for-syntax, with a snippet in the middle. Any plugins listed after the snippet will fail to load/download.

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Linux Nicks-Laptop 5.4.0-17.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.4-23.2~bullseye (2020-02-01) x86_64 GNU/Linux`

**Comment by psprint** [comment]
Thanks, it's fixed.
