### ISSUE TITLE
Compilation fails with parse error on zimfw/input

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/zinit#273]
**Describe the bug**
Compilation fails on [zimfw/input](https://github.com/zimfw/input/blob/master/init.zsh), but if I compile it manually with `zcompile`, no errors occur. Probably something similar to #263.

**To Reproduce**
```
❯ zinit light zimfw/input    

Downloading zimfw/input... (as zimfw/input...)

Cloning into '/Users/marlon/.zinit/plugins/zimfw---input'...
▀ ███████████ OBJ: 100, PACK: 67/83, COMPR: 100%  
Compiling init.zsh.
.zinit-compile-plugin:45: parse error near `bindkey'
.zinit-compile-plugin:zcompile:42: can't read file: /Users/marlon/.zinit/plugins/zimfw---input/init.zsh
Compilation failed. Don't worry, the plugin will work also without compilation
Consider submitting an error report to Zinit or to the plugin's author.
``` 

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version: macOS Catalina version 10.15.3 (19D76)

**Comment by psprint** [comment]
Thanks. it's fixed. The sourced file is intensively using `SHORT_LOOPS`, so now `zcompile` is being run after setting this option.
