### ISSUE TITLE
New plugin installation fails

### ISSUE THREAD

**Issue by gin2be** [zdharma/zinit#278]
**Describe the bug**
I can't install new plugins.

**To Reproduce**
just open the terminal

```
source ~/.zinit/bin/zinit.zsh

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit ice from"gh-r" as"program" mv"ripgrep* -> ripgrep" pick"ripgrep/rg"
zinit light BurntSushi/ripgrep
zinit ice from"gh-r" as"program" pick"*/ghq"
zinit load x-motemen/ghq
zinit ice from"gh-r" as"program"
zinit load junegunn/fzf-bin
```

![bug](https://user-images.githubusercontent.com/44626616/76066286-aee06800-5fd0-11ea-93c3-9f45f8fa26ca.png)

**Expected behavior**
to be able to install plugins.

**Versions:**
 - $ZSH_VERSION == 5.4.2
 - Operating system name and version (uname -a):
  `Linux ubuntu-bionic 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
https://github.com/zdharma/zinit/commit/2d14c8b9e8f12a7103b0d21fab4fc4ca995d325d works fine but https://github.com/zdharma/zinit/commit/8cd6c0796a316dd7b7ca6a9abc9d75df0762d659 failed

**Comment by psprint** [comment]
It's fixed, thanks.

**Comment by gin2be** [comment]
It works. thanks.
