### ISSUE TITLE
Wiki link is broken in README.md

### ISSUE THREAD

**Issue by punitsoni** [zdharma/zinit#279]
In main readme file following section the link to wiki is broken.

> [Click here to read the introduction to Zinit.](http://zdharma.org/zinit/wiki/INTRODUCTION/) It explains basic usage and some of the more unique features of Zinit such as the Turbo mode. If you're new to Zinit we highly recommend you read it at least once.

**Comment by n0nick** [comment]
FWIW there seems to have been some recent drama with this repo:
https://www.reddit.com/r/zinit/comments/ffohjj/zinit_project_status_paranoia/

I just found out about Zinit today and am not at all familiar with any of the details. But possibly related.

**Comment by punitsoni** [comment]
Yeah. I found the whole discussion on reddit regarding this drama. I was just getting started using a zsh plugin manager and found zinit to be the most recommended one. But, now I am not sure. Without wiki there is no way for me to understand how this work. I think I am going to probably look into other options like Zplug.

**Comment by NICHOLAS85** [comment]
To those following this issue, the wiki is back up. https://github.com/zdharma/zinit/issues/286#issuecomment-605176261

**Comment by psprint** [comment]
The Wiki was gone because of the domain expiration. Now it's back up.
