### ISSUE TITLE
Is there a way to run a command _before_ loading?

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/zinit#283]
`atload` runs _after_ loading and `atinit` _sometimes_ runs before loading but not always.

Is there a syntax to get a command to consistently run _every time before loading_?

**Comment by NICHOLAS85** [comment]
From what I understand, atinit always runs before any plugin loading occurs. For example here: https://github.com/zdharma/zinit/blob/5ddb033342ffa074e85e809ba83757801ff00e71/zinit.zsh#L1170. Is there a specific workflow that’s breaking for you? It may be useful to include the code snippet that isn’t functioning the way you believe it should.

**Comment by marlonrichert** [comment]
I haven't been able to reproduce this behavior anymore.
