### ISSUE TITLE
Completions not completing in new shells after parallel zi update

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#284]
**Describe the bug**
After running a parallel update and opening a new shell, tab completions do not populate. I have to run `zicompinit` for tab completions to populate again. This only occurs using the `--parallel` option for `zinit update`

**To Reproduce**
```
$ zinit update --parallel
...
$ exec zsh
$ ls <TAB>
# No completions popup
```

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Linux Nicks-Laptop 5.5.0-9.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.5-12.1~bullseye (2020-03-12) x86_64 GNU/Linux`

**Additional context**
Does not occur with the normal `update` command

**Comment by psprint** [comment]
Yes, sometimes the completions break, or maybe even always. I would recommend to run `zi compinit` instead of the regular `compinit`, it does more to reset the completions. I will look for a time to check upon this and a small donation like $5 or $10 would be helpful.

**Comment by NICHOLAS85** [comment]
Of course, have you looked into any other donations options besides paypal? I've previously attempted donating but ran into issues. I'll be happy to try again now though.

**Comment by psprint** [comment]
There's Ko-Fi account, available through the Sponsor button

śr., 8 kwi 2020, 23:44 użytkownik NICHOLAS85 <notifications@github.com>
napisał:

**Comment by NICHOLAS85** [comment]
Ah, it seems that still processes through Paypal. It wasn't accepting my card, but I've fixed it now.

**Comment by psprint** [comment]
Thanks for the donation. I should be working within the next 7 days.

czw., 9 kwi 2020, 23:13 użytkownik NICHOLAS85 <notifications@github.com>
napisał:

**Comment by psprint** [comment]
It should be fixed. Could you check?

**Comment by NICHOLAS85** [comment]
The issue seems to still be present with as of 872be10400983c2696034e73e18a6ce01ae2f4cf

**Comment by psprint** [comment]
It should be fixed now.

**Comment by NICHOLAS85** [comment]
Thanks! Issue fixed
