### ISSUE TITLE
I have a problem at startup

### ISSUE THREAD

**Issue by felipesuri** [zdharma/zinit#285]
Whenever I start my terminal (in linux mint) it returns the following information. And I don't know how to solve it.

[Image](http://i.imgur.com/9kYsfBX.png)

**Comment by psprint** [comment]
It looks like you have a following line in zshrc:

```zsh
zinit load buonomo/yarn-completion#/ZPLUGIN
```

Why? I don't know. However, the line should be probably:


```zsh
zinit load buonomo/yarn-completion
```
