### ISSUE TITLE
zdharma website down

### ISSUE THREAD

**Issue by sparr** [zdharma/zinit#286]
https://downforeveryoneorjustme.com/zdharma.org

Zdharma.org Status
Is zdharma.org down right now?
It's not just you! zdharma.org is down.

**Comment by psprint** [comment]
Yes, I need to pay for the domain. A little funds for it would be appreciated, like $5 or $10. If you want, you can donate using the links at top of the Readme.

**Comment by sparr** [comment]
I set up a Patreon subscription but it won't process for a week. Would be awesome if you had an immediate non-Paypal option.

http://anythingbutpaypal.com

**Comment by psprint** [comment]
Great, thanks! I'll think about some other donating option.

**Comment by quasipedia** [comment]
Leaving the difficult topic of funding of FLOSS projects aside, I would suggest that you move the documentation of the project on the same platform as the code (in this case GitHub).  This is just a good practice.  An external site should be used for branding/SEO, fundraising, etc...

**Comment by psprint** [comment]
Ok, I've extended the domain ownership. The site is up again. Thanks.
