### ISSUE TITLE
Latest Xcode & Command Line Tools removes SVN tools.

### ISSUE THREAD

**Issue by ahmedelgabri** [zdharma/zinit#293]
**Describe the bug**
The subversion command line tools are no longer provided by Xcode in the latest Xcode.

**To Reproduce**

- Update macOS to 10.15.4
- Update Command Line tools for Xcode 11.4
- Try to install/update a snippet, for example `OMZ::plugins/gpg-agent`

**Expected behavior**
When I tried to update a snippet _which by default uses SVN_ I got this error

```
svn: error: Failed to locate 'svn'.
svn: error: The subversion command line tools are no longer provided by Xcode.
```

**Screenshots**

<img width="535" alt="Screenshot 2020-03-31 at 11 37 05" src="https://user-images.githubusercontent.com/63876/78011509-f6de7a80-7343-11ea-9b35-77967e242648.png">

**Versions:**
 - $ZSH_VERSION == `5.7.1`
 - Operating system name and version (uname -a): `Darwin pandoras-box 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin`

**Comment by psprint** [comment]
Thanks. Soon I'll provide a snippet that installs Subversion.

**Comment by psprint** [comment]
Here's the snippet. It requires up to date Zinit and z-a-as-monitor annex:

```zsh
zi as"null|monitor" dlink"https://.*/subversion-%VERSION%.tar.bz2" \
    atclone'zpextract --move --auto; print -P \\n%F{75}Building Subversion%f; ./configure \
        --prefix="$ZPFX" >/dev/null && make install >/dev/null  && print -P \
        \\n%F{34}Installation of Subversion succeeded.%f || \
        print -P \\n%F{160}Installation of Subversion failed.%f' for \
            https://subversion.apache.org/download.cgi
```

**Comment by ahmedelgabri** [comment]
This is what I get when I try the snippet you provided

<img width="1615" alt="Screenshot 2020-04-01 at 21 19 57" src="https://user-images.githubusercontent.com/63876/78177563-9b54df80-745e-11ea-9e0a-7c1597fa0999.png">

**Comment by psprint** [comment]
Here's an updated snippet that doesn't use the Apache Portable Runtime dependency:
```zsh
zi as"null|monitor" dlink"https://.*/subversion-%VERSION%.tar.bz2" \
    atclone'zpextract --move --auto; print -P \\n%F{75}Building Subversion...\\n%f; ./configure \
        --prefix="$ZPFX" --without-apr >/dev/null && make >/dev/null && print -P \
        \\n%F{75}Installing Subversion to $ZPFX...\\n%f && make install >/dev/null && print -P \
        \\n%F{34}Installation of Subversion succeeded.%f || \
        print -P \\n%F{160}Installation of Subversion failed.%f' \
    atpull'%atclone' for \
            https://subversion.apache.org/download.cgi
```

Also, I've created a [Zsh package](https://github.com/Zsh-Packages/subversion] for the Subversion tools. It has the `no-apr` profile that also doesn't use Apache Portable Runtime. For people that want to use APR, there's an [APR Zsh package](https://github.com/Zsh-Packages/apr] too.
