### ISSUE TITLE
Extraction of .deb files

### ISSUE THREAD

**Issue by amanjitsk** [zdharma/zinit#295]
**Is your feature request related to a problem? Please describe.**
Some packages default to downloading the .deb file on ubuntu, when downloading from github releases using `from"gh-r"` (an example of this would be [charmbracelet/glow](https://github.com/charmbracelet/glow)). This is not currently automatically handled.

**Describe the solution you'd like**
Automatic extraction of .deb files.

**Describe alternatives you've considered**
Manual extraction using [dtrx](https://github.com/moonpyk/dtrx)

Thanks for the amazing project!

**Comment by psprint** [comment]
OK, I've added DEB package support :) It requires Debian tools. I'll now add RPM support.

**Comment by psprint** [comment]
I've added RPM support too.
