### ISSUE TITLE
Brew command-not-found doesn't work through zinit

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/zinit#296]
**Describe the bug**
If I `source` the script located at https://github.com/Homebrew/homebrew-command-not-found/blob/master/handler.sh, I get the expected behavior, but when I try to use it through `zinit`, it does not work.

**To Reproduce**
```shell
$ zinit snippet https://github.com/Homebrew/homebrew-command-not-found/blob/master/handler.sh
$ when
```

**Expected behavior**
```shell
The program 'when' is currently not installed. You can install it by typing:
  brew install when
```

**Actual behavior**
```shell
zsh: command not found: when
```

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by marlonrichert** [comment]
Never mind, the problem was on my end. Later on in my `.zshrc`, I also had `zinit light-mode for Tireg/zsh-macos-command-not-found` and that plugin just doesn't work.

**Comment by psprint** [comment]
OK, good that it resolved
