### ISSUE TITLE
Please allow disabling the git output beauty enhancer

### ISSUE THREAD

**Issue by cr1st1p** [zdharma/zinit#297]
**Is your feature request related to a problem? Please describe.**
I am running installs unattended via Saltstack (configuration management) and the git-process-output.zsh used to colorize/beautify the output of 'git clone' ends up in a very bad shape in the log files.

Probably the same script is also the source of some error lines like:
```
tput: No value for $TERM and no -T specified
```

**Describe the solution you'd like**
I need a way to tell the install script (doc/install.sh) to not use git-process-output.zsh
Same for zinit-install.zsh (used to install plugins?)

**Describe alternatives you've considered**
Did not, yet.

**Additional context**
Again, it is about running the installs via batch scripts, without a terminal.

**Comment by psprint** [comment]
I've added a test for the $TERM var. Hope that's enough.

**Comment by cr1st1p** [comment]
Thank you for the fast change!

The fix works partially : 
a) Please also remove the '--progress' flag from git clone. It is implicit except for the cases where git detects a lack of terminal (my case).

b) Shouldn't '$TERM' be double quoted, for safety, in the condition check?
```
if [[ -n $TERM ]] {
...
```
Regards.

**Comment by psprint** [comment]
a) OK, there's no progress bar when no TERM,
b) no, [[ doesn't require quoting.
