### ISSUE TITLE
tput error messages for each plugin installed, in non interactive mode

### ISSUE THREAD

**Issue by cr1st1p** [zdharma/zinit#298]
**Describe the bug**
I'm installing zinit and plugins in non interactive mode.
Error log shows many
```
tput: No value for $TERM and no -T specified
```
It looks to appear twice per plugin installed, and I think it comes from the following lines in 
git-process-output.zsh  which are not guarded against the '$TERM" variable:
```
(( $+ZINIT_CIVIS )) && eval $ZINIT_CIVIS
....
(( $+ZINIT_CNORM )) && eval $ZINIT_CNORM
```

**To Reproduce**
Setup a .zshrc that declares some zinit plugins to load and run zsh in non interactive mode (like a ssh command)

**Expected behavior**
No error messages

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Manjaro, linux

**Additional context**

**Comment by psprint** [comment]
It's correct now, thanks
