### ISSUE TITLE
Wrong architecture requested for gh-r on rpi4

### ISSUE THREAD

**Issue by zewelor** [zdharma/zinit#299]
**Describe the bug**
Wrong architecture is being detected, for downloading gh-r releases.

**To Reproduce**
On rpi add junegunn/fzf-bin from gh-r

**Expected behavior**
version for arm7 https://github.com/junegunn/fzf-bin/releases . Probably it should look for both armv7l and arm7

**Screenshots**
Downloading junegunn/fzf-bin... (as junegunn/fzf-bin...)
(Requesting `fzf-0.21.1-darwin_386.tgz'...)

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

**Additional context**
Rpi4, official raspbian ( 32 bit )
From looking at code, I believe its not handled here: https://github.com/zdharma/zinit/blob/master/zinit-install.zsh#L1362

**Comment by psprint** [comment]
Could you share:

```zsh
print $CPUTYPE $MACHTYPE
```

**Comment by zewelor** [comment]
armv7l arm

**Comment by psprint** [comment]
It's fixed, could you check?

**Comment by zewelor** [comment]
Now it downloaded:
(Requesting `fzf-0.21.1-linux_arm5.tgz'...)

file .zplugin/plugins/junegunn---fzf-bin/fzf                                                                                                                                                                     
.zplugin/plugins/junegunn---fzf-bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked

Binary works, but probabaly version for arm7 would be better optimized. Thanks for quick looking into this.

**Comment by psprint** [comment]
It should be fixed.

**Comment by zewelor** [comment]
Works great now !
