### ISSUE TITLE
Clone failed (code: 141) with any new plugins

### ISSUE THREAD

**Issue by thuandt** [zdharma/zinit#300]
**Describe the bug**
zinit return `Clone failed (code: 141)` when try install new plugin

I searched on Google and I found 2 links. It's said something wrong with `pipe` and `git`:
- https://www.ingeniousmalarkey.com/2016/07/git-log-exit-code-141.html
- https://stackoverflow.com/questions/54999974/why-does-git-log-return-exit-code-141-after-exit-and-how-can-i-avoid-it

Here is my config for reference: 

+ Git config: https://github.com/thuandt/dotfiles/blob/master/tools/vcs/git/.gitconfig
+ zshrc: https://github.com/thuandt/dotfiles/blob/master/shells/zsh/zshrc

**To Reproduce**
- Delete or add new plugins then open new terminal tab

**Expected behavior**
zinit can clone new plugins

**Screenshots**
![](https://i.imgur.com/pbjKN4q.png)

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a):
```
Linux mrtux-desktop 5.6.2-xanmod2 #0 SMP PREEMPT Tue Mar 31 01:03:21 -03 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Git: `git version 2.26.0`

**Comment by psprint** [comment]
I've pushed a commit that tries to workaround the problem, could you retry and show the result?

**Comment by thuandt** [comment]
@psprint thanks you for quick reply. Look like it's gone.

![image](https://user-images.githubusercontent.com/847996/79077891-bf51d400-7d2e-11ea-84fd-572e74cf9253.png)

**Comment by psprint** [comment]
Ok. The issue is pretty weird though, nobody else reported failing of git
piping through the progress bar script.

niedz., 12 kwi 2020, 21:30 użytkownik Thuan Duong <notifications@github.com>
napisał:
