### ISSUE TITLE
Could zinit manage itself, just like zplug.

### ISSUE THREAD

**Issue by aQuaYi** [zdharma/zinit#301]
**Is your feature request related to a problem? Please describe.**
When I input `zinit update` in zsh, I wanna the zinit and its all plugs up to date. But now, I have to type `zinit self-upate` more.

**Describe the solution you'd like**
In zplug, add below to .zshrc

```zsh
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
```
zplug could manage itself.
https://github.com/zplug/zplug#let-zplug-manage-zplug

OR

just add self-update function to `zinit update` command.

**Comment by psprint** [comment]
The self-managing isn't a good idea, as it is purely symbolic – under the hood, it would mean just calling of the `self-update` and not using the code for updating the plugins. I will however think about adding the `self-update` to `update`.

**Comment by psprint** [comment]
OK, it is done, now `update --all` or `update` does `self-update` too.

**Comment by aQuaYi** [comment]
Thanks very much.
