### ISSUE TITLE
High latency when try to use man command.

### ISSUE THREAD

**Issue by RoadToDream** [zdharma/zinit#305]
**Describe the bug**
High latency when try to use man command, because of the large number of manuals. Probably because that zsh is indexing the items as I am typing. 
**To Reproduce**

**Expected behavior**
Should not indexing the manuals until I type tab key.

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Darwin Jiaweis-MBP 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Additional context**

**Comment by psprint** [comment]
I think that you're referring to fast-syntax-highlighting. The issue should be solved there.

**Comment by RoadToDream** [comment]
> I think that you're referring to fast-syntax-highlighting. The issue should be solved there.

Thanks for the reply! 
I prefer I am not praying for a new add-in, that might be an overkill. Maybe there would be a switch that controls whether zsh will try to find suggestions in realtime or just find suggestions after I have typed the "tab". As I really don't need zsh to lookup every possibility when I am typing as I am pretty sure what I am typing is right.

**Comment by RoadToDream** [comment]
May I ask why is it labeled with non-issue? Like nobody else has the issue? 
I may upload a video clip to explain why is the latency can not be ignored.

**Comment by RoadToDream** [comment]
![zinit_latency](https://user-images.githubusercontent.com/8088354/79791018-7c30cb80-8301-11ea-83c9-b42bbb6c0dfa.gif)

**Comment by NICHOLAS85** [comment]
I believe it's labeled non-issue as this is relating to https://github.com/zdharma/fast-syntax-highlighting/issues/179 and not Zinit. Track the issue at that page to stay up to date.

**Comment by RoadToDream** [comment]
Oh, sorry for confusing. But I don't this this problem is related with fast-syntax-highlighting plug-in. As the performance dropping persists even if I have disabled that.

**Comment by RoadToDream** [comment]
Oh, I see. Thanks for comment back!
