### ISSUE TITLE
Use tar.gz if dpkg-deb is not available

### ISSUE THREAD

**Issue by davidosomething** [zdharma/zinit#307]
For the following repo, as a github release, the default linux bpick would find a `.deb` package before the tar.gz
https://github.com/cli/cli/releases

This is only preferable on debian/ubuntu where dpkg-deb is innately available.
zinit should prefer the .tar.gz since it would work across all distros

**Comment by psprint** [comment]
It's a good idea, I'll implement this.

**Comment by psprint** [comment]
It's done. Thanks.
