### ISSUE TITLE
report thinks path elements with spaces added before plugin load were added by plugin

### ISSUE THREAD

**Issue by olets** [zdharma/zinit#309]
I have a plugin which doesn't add to `$PATH`. Running `zinit report` on it says the plugin adds elements to `$PATH`. The specific elements it lists are all elements in `$PATH` with spaces (escaped or not) in their paths.

**To Reproduce**

Have some PATH elements with spaces, then import a plugin, then run `report` on the plugin.

```shell
# .zshrc
# ---snip---
export PATH="some/path with unescaped/space:$PATH"
export PATH=some/path\ with\ escaped/space:$PATH
zinit load some/plugin/that/does/not/touch/path
```

```shell
% zinit report some/plugin/that/does/not/touch/path
# ---snip---
PATH elements added:
some/path with unescaped/space
some/path with escaped/space
# ---snip---
```

Note the order. This will not reproduce the bug:

```shell
# .zshrc
# ---snip---
zinit load some/plugin/that/does/not/touch/path
export PATH="some/path with unescaped/space:$PATH"
export PATH=some/path\ with\ escaped/space:$PATH
```

**Expected behavior**

`zinit report` only lists PATH elements added by the plugin.

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): macOS 10.14 (Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64)

And I ran `zinit self-update` today.

**Additional context**

Discovered running `zinit report` on [zsh-abbr](https://github.com/olets/zsh-abbr). Haven't tested every plugin I'm using, but confirmed that it does happen with [fast-syntax-highlighting](https://github.com/zdharma/fast-syntax-highlighting) and does _not_ (edit! I initially wrote "does") happen with [zsh-prompt-benchmark](https://github.com/romkatv/zsh-prompt-benchmark).

**Comment by psprint** [comment]
I've fixed the problem, thanks.

**Comment by olets** [comment]
😮 🏃‍♂️🏅fastest bug fix ever

Confirmed it's fixed. Sorry for the duplicate issue, didn't see it when I searched
