### ISSUE TITLE
zinit does not pick .tar.gz archive if there is .asc control sum

### ISSUE THREAD

**Issue by mkjmdski** [zdharma/zinit#311]
**Describe the bug**
Happened when trying to install helm with zinit

**To Reproduce**
```
    zinit ice from"gh-r" as"program" mv"helm* -> helm"
    zinit load helm/helm
```

**Expected behavior**
download helm.tar.gz not helm.tar.gz.asc

**Screenshots**
```
Downloading helm/helm... (as helm/helm...)
(Requesting `helm-v3.2.0-rc.1-linux-amd64.tar.gz.asc'...)
ziextract: WARNING: didn't recognize the archive type of `helm-v3.2.0-rc.1-linux-amd64.tar.gz.asc' (no extraction has been done).
renamed 'helm-v3.2.0-rc.1-linux-amd64.tar.gz.asc' -> 'helm'
```
**Versions:**
 - $ZSH_VERSION == 5.4.2
 - Operating system name and version (uname -a): Linux planet 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by psprint** [comment]
The problem is that `helm` uses external hosting for the binaries. You can download it with `z-a-as-monitor` annex, however.

**Comment by psprint** [comment]
An example snippet to download `helm` using the `z-a-as-monitor` annex:

```zsh
zinit as"monitor|command" pick"**/helm" extract \
    dlink=https://get.helm.sh/helm-'%VERSION%'-linux-amd64.tar.gz for \
        https://github.com/helm/helm/releases
```

I would recommend using `z-a-bin-gem-node` annex for its `sbin''` ice – the snippet then will be:

```zsh
zinit as"monitor|null" sbin"**/helm" extract \
    dlink=https://get.helm.sh/helm-'%VERSION%'-linux-amd64.tar.gz for \
        https://github.com/helm/helm/releases
```

**Comment by mkjmdski** [comment]
what is the exact difference between those two? I am currently migrating from zplug to zinit and would be cool to know the details :)

**Comment by ahmedelgabri** [comment]
I'm having the same issue with `hub` & the binaries are hosted on github https://github.com/github/hub/releases

```
ziextract: WARNING: didn't recognize the archive type of `hub-darwin-amd64-2.14.2.tgz' (no extraction has been done).
```

**Comment by thuandt** [comment]
@ahmedelgabri Revert to commit `ffca5f8c` fix my issue about extract tar ball

@psprint seem some commits in last 4 days cause `ziextract` issue

**Comment by 5ilvers** [comment]
may not be the same cause, noticed this ticket was opened > a month ago.

**Comment by hrai** [comment]
> @ahmedelgabri Revert to commit `ffca5f8c` fix my issue about extract tar ball
> 
> @psprint seem some commits in last 4 days cause `ziextract` issue

I'm having similar issue with `ziextract `- https://github.com/zdharma/zinit/issues/340

**Comment by psprint** [comment]
The `extract''` problem has been resolved.

@mkjmdski: The As-Monitor annex-utilizing version uses a very different technique to download the binary.
