### ISSUE TITLE
zinit is not leveraging $TMPDIR

### ISSUE THREAD

**Issue by pschmitt** [zdharma/zinit#313]
**Describe the bug**
Using [Termux](https://termux.com/) I noticed that a few errors were spat out when updating using `zinit update -p 20`:

```
[...]
2019-10-24 1eb4759 better completion with filetypes
2019-10-23 f6eff10 Add cppcheck support
Updating a6e641b..d4e54f1
Fast-forward
Installed 146 completions. They are stored in $INSTALLED_COMPS array. .zinit-install-completions:67: no such file or directory: /tmp/zinit.installed_comps.20640.lst
.zinit-install-completions:68: no such file or directory: /tmp/zinit.skipped_comps.20640.lst
[7]    done       .zinit-update-or-status update "$user" "$plugin" &>>| $PUFILE
The update took 55.71 seconds
```
[This is due to `/tmp` being inaccessible in Termux](https://wiki.termux.com/wiki/Differences_from_Linux)

**To Reproduce**
Run `zinit update` on Termux.

**Expected behavior**
zinit shouldn't assume /tmp is accessible.
If `$TMPDIR` is set use its value instead of assuming `/tmp`.
`TMPDIR=${TMPDIR:-/tmp}`

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a):
`Linux localhost 4.4.218-Xiaomi_SDM660-LA.UM.8.2.r1-06300+ #1 SMP PREEMPT Fri Apr 17 22:12:22 MSK 2020 aarch64 Android`

**Comment by psprint** [comment]
It's fixed, thanks.
