### ISSUE TITLE
Provide an option for `zinit create` to authenticate to GitHub thru SSH instead of HTTPS

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/zinit#314]
`zinit create` asks me for my GitHub password. I don't want to enter that. If `zinit create` would use SSH instead of HTTPS, then it wouldn't need to ask for my password, because I would be authenticated through `ssh-agent`.

**Comment by MunifTanjim** [comment]
Some people prefers to use the HTTPS method. So saying "should authenticate to GitHub thru SSH" sounds forceful. Maybe you want request additional feature for SSH authentication instead?

Also, you can use a git credential helper to cache your password. So, you'll just need to enter the password once.

If you're using Ubuntu, you can use this script to set it up:

```sh
sudo apt install build-essential libsecret-1-dev libglib2.0-dev
cd "/usr/share/doc/git/contrib/credential/libsecret"
sudo make
local -r helper="/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret"
git config --global credential.helper "${helper}"
```

Ref:
- https://www.git-scm.com/docs/gitcredentials
- https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

**Comment by pschmitt** [comment]
That's not zinits job in my opinion.

The easiest way to make this work is to just setup git correctly.

```git
[url "git@github.com:"]
  pushInsteadOf = https://github.com/
```

**Comment by marlonrichert** [comment]
@pschmitt @MunifTanjim Thanks for your input. I changed my request to provide an option to authenticate thru SSH instead of change the default. Is that good enough to remove your downvote? 🙂
