### ISSUE TITLE
delete --clean doesn't remove shims created by sbin annex

### ISSUE THREAD

**Issue by Gerrit-K** [zdharma/zinit#319]
Reporting a (minor) bug again. It's not causing any inconvenience. It's just for the sake of completeness.

I recently noticed that the syntax highlighting still reported my `bat` as a valid command (green color), although I deleted it a couple of days ago. Turned out the plugin directory was removed but the shim created by the sbin ice (from `z-a-bin-gem-node`) still resided in the bin dir. It should be pretty easy to reproduce as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/8766565/80492008-bcc4c080-8963-11ea-9913-0bbdc88c1fdb.png)

Edit: deleting the plugin manually using `zi delete sharkdp/bat` _does_ remove the shim.

**Comment by psprint** [comment]
It's implemented, thanks.
