### ISSUE TITLE
zinit doesn't load completions until 'zinit creinstall' is run

### ISSUE THREAD

**Issue by hrai** [zdharma/zinit#321]
**Describe the bug**
I have the setup below to call creinstall when zsh starts. But this takes a while (~12s).
```
zinit ice blockf atload'zinit creinstall -q .'
zinit light zsh-users/zsh-completions
```

If I just have the following block, the auto-completions for `zi <tab>` doesn't suggest desired options. I don't get the options `cd, ls, status, report` etc. Also, `zi cd <tab>` doesn't give the list of plugins installed.
```
zinit ice blockf atload'zinit creinstall -q .'
zinit light zsh-users/zsh-completions
```

`zi times` prints below:
- 6 ms - zsh-users/zsh-completions (with creinstall)
- 13299 ms - zsh-users/zsh-completions (without creinstall)

Calling `creinstall` seems to resolve the issue but it's too slow.

I'm loading `zsh-completions` after all the plugins.

Am I missing anything?

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
The print on the screen when the app loads with `creinstall`.
![image](https://user-images.githubusercontent.com/4055444/80575068-451b9200-8a46-11ea-8b05-088d8b7942bd.png)

**Versions:**
 - $ZSH_VERSION == 5,8
 - Operating system name and version (uname -a): Linux 4.4.0-19613-Microsoft #1000-Microsoft Thu Apr 17 15:57:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
I'm running this on Ubuntu 20.x WSL.

**Comment by mcanevet** [comment]
For me completion does do work at all if I does not launch append `atload'zinit creinstall -q .'` (thanks for the tip by the way).

**Comment by hrai** [comment]
It seems to be much faster after I upgraded to wsl2.

**Comment by psprint** [comment]
I think that it should been `atclone'zinit creinstall -q' atpull'%atclone'`, then it'll be fast.

**Comment by hrai** [comment]
If I do that, `echo $INSTALLED_COMPS` returns empty string.

![image](https://user-images.githubusercontent.com/4055444/81876538-4a401b80-95c6-11ea-9e8f-3851e89e0c68.png)

**Comment by NICHOLAS85** [comment]
You do not need to run `zinit creinstall` every time the plugin loads using `atload`. This installs the completions from fresh every time your plugin loads which can be slow. Once completions are installed they are stored to a cache and initialized in your current session via some sort of `compinit` call usually found at the end of your zshrc. More info on how to set that up can be found here: https://github.com/zdharma/zinit#calling-compinit-without-turbo-mode. The ices psprint is suggesting force the plugin to have its completions installed on clone and atpull(when the plugin updates), which are the only times it should be necessary to do so. `$INSTALLED_COMPS` is just a variable used to identify recently installed completions to my knowledge.

**Comment by hrai** [comment]
As per the doco, I've added the code below to .zshrc near the bottom after loading all the plugins.

```
autoload -Uz compinit
compinit

zinit cdreplay -q   
```

Output of `echo $INSTALLED_COMPS` is still empty.

**Comment by psprint** [comment]
The issue with the `$INSTALLED_COMPS`being empty on plugin update has been resolved.

**Comment by hrai** [comment]
I tried it but still no good.

![image](https://user-images.githubusercontent.com/4055444/83599234-00d46200-a5af-11ea-8851-a788d506581a.png)
