### ISSUE TITLE
`$ zinit creinstall -q <PATH>` does not silence all output

### ISSUE THREAD

**Issue by alichtman** [zdharma/zinit#326]
**Describe the bug**

`$ zinit creinstall -q <PATH>` still shows one line of output:

```
Installed 1 completions. They are stored in $INSTALLED_COMPS array.
```

**To Reproduce**

```bash
$ zinit creinstall -q $ZDOTDIR/completions
Installed 1 completions. They are stored in $INSTALLED_COMPS array.
```

**Expected behavior**

`-q` should silence ALL output. (Or maybe add `-Q` to silence ALL output and leave `-q` to silence most output?)

**Versions:**

```
$ zsh --version && sw_vers
zsh 5.8 (x86_64-apple-darwin18.7.0)

ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G3020
```

**Comment by psprint** [comment]
OK, I've added a new option `-Q` that silences all output.

**Comment by alichtman** [comment]
Great, thank you!
