### ISSUE TITLE
Snippets are broken by zinit update

### ISSUE THREAD

**Issue by GrzegorzKozub** [zdharma/zinit#328]
**Describe the bug**
Updating snippets with `zinit update` fails to download them due to HTTP 404 Not Found and breaks the installed snippets. Clean install works fine.

**To Reproduce**
1. Add a snippet to your `.zshrc`, for example:
```
zinit ice wait lucid as'completion'
zinit snippet OMZ::plugins/docker-compose/_docker-compose
```
2. Restart zsh and observe a proper snippet installation:
```
Setting up snippet           OMZ::plugins/docker-compose/_docker-compose
Downloading `OMZ::plugins/docker-compose/_docker-compose' (with curl, wget, lftp)...
############################################## 100,0%
############################################## 100,0%
Installed 0 completions. They are stored in $INSTALLED_COMPS array.
Skipped installing 1 completions. They are stored in $SKIPPED_COMPS array.
```
3. See that `snippets/OMZ::plugins--docker-compose/_docker-compose/_docker-compose` file exists and the related completion is actually working.
4. Run `zinit update` and observe a failed update: 
```
Updating snippet OMZ::plugins/docker-compose/_docker-compose
Downloading `OMZ::plugins/docker-compose/_docker-compose' (with curl, wget, lftp)...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
Download failed. No available download tool? (one of: curl, wget, lftp, lynx)
```
5. The `snippets/OMZ::plugins--docker-compose/_docker-compose/_docker-compose` file is gone now and the related completion stops working.

**Expected behavior**
Snippets are updated and not broken.

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): `Linux drifter 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64 GNU/Linux`

**Comment by namangoy** [comment]
Still facing issue for docker
Same for
```
zinit ice as"completion"
zinit snippet OMZP::docker/_docker
```

**Comment by psprint** [comment]
The issue is fixed.
