### ISSUE TITLE
Internal `key` param overrides the one from zkbd

### ISSUE THREAD

**Issue by nisavid** [zdharma/zinit#329]
**Describe the bug**
Some plugins, such as [marlonrichert/zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete), rely on accessing the parameter named `key`.  If set, this parameter is expected to be a global associative array (i.e. `typeset -g -A`) that maps user-friendly keyboard key names (such as `Up`) to the corresponding escape sequences emitted by the current terminal (such as `^[[A`).  In typical usage, this parameter is declared and defined in a script, specially named for the terminal environment, in the directory `${ZDOTDIR:-$HOME}/.zkbd` (the `zkbd` autoloadable function—included with Zsh—interactively generates these files).

Within a number of its internal functions, Zinit also defines a `key` parameter, locally overriding the global one.  While a plugin is loading, the parameter is set to an empty string (i.e. `typeset key=''`).  This causes plugins that rely on the standard `key` parameter to fail to load.  In the case of marlonrichert/zsh-autocomplete, an error message is emitted at load time:

```
…/marlonrichert---zsh-autocomplete/zsh-autocomplete.plugin.zsh:66: key:assignment to invalid subscript range
```

I haven't investigated in detail how Zinit is handling its `key` parameter beyond what is reported above.  One way or another, to resolve this issue, when a plugin is loaded (i.e. when its plugin file(s) is/are sourced), the parameter should be set to its global value (if globally set) or unset (if globally unset).

**To Reproduce**
`zinit load marlonrichert/zsh-autocomplete`

**Expected behavior**
The plugin marlonrichert/zsh-autocomplete is loaded in a manner such that its code sees the global parameter `key` (if it is globally set) or an unset parameter `key` (if it is globally unset).

**Versions:**
 - $ZSH_VERSION == zsh 5.8 (x86_64-pc-linux-gnu)
 - Operating system name and version (uname -a): Linux aero 5.5.0-pf8-aero #3 SMP PREEMPT Tue Mar 31 12:09:35 EDT 2020 x86_64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz GenuineIntel GNU/Linux

**Comment by NICHOLAS85** [comment]
Taking a quick look at Zinits loading code, specifically at snippet loading https://github.com/zdharma/zinit/blob/a81b97037fbf834d05a3a4d9e264ce7540108d99/zinit.zsh#L1384-L1390, I see that `key` is used in Zinit annex loading. It seems the significance of the name `key` doesn't matter in these evocations so I created a quick diff altering it. This fixed the issue when using snippet loading. You can apply it yourself until something is done upstream about the issue:
[snippetkeyvarfix.txt](https://github.com/zdharma/zinit/files/4589491/snippetkeyvarfix.txt)

I haven't looked at plugin loading, turbo loading and light but I have a hunch the same issue is shared in those as well.

**Comment by nisavid** [comment]
For now, I'm using [this patch](https://github.com/nisavid/zinit/commit/d0f27fb1c486978d2e4cbaa6c7da9b9e7045f73f) to work around the issue with the `key` param.  This is merely a stopgap, as it renames all `key` parameters to `key_`, thereby shifting the problem to `key_` without fundamentally solving it.  Ideally, the global namespace should be effectively unaltered when a plugin is being sourced—in other words, Zinit's sourcing should be functionally equivalent to `.` from a plugin's perspective.  Whether or not it's worth the effort to try to achieve this (without noticeably degrading performance), or whether something like the above-referenced patch should be merged in for now to reduce the impact of the fundamental problem, is @psprint's call.

**Comment by psprint** [comment]
Thanks for the report. I've added an uncommon three-underscores prefix to each variable in the three functions that take part in loading of the plugin. Thus, collisions shouldn't happen anymore.

**Comment by nisavid** [comment]
LGTM.  If it turns out that someone has a plugin that relies on a global `___key`, well… they can open a separate issue.

**Comment by psprint** [comment]
Sourcing a plugin without any global variables is in practice very difficult and in theory impossible.
