### ISSUE TITLE
Recent commits broke skywind3000/z.lua plugin function

### ISSUE THREAD

**Issue by vtnpp** [zdharma/zinit#331]
**Describe the bug**

I'm using [skywind3000/z.lua](https://github.com/skywind3000/z.lua) plugin to quickly cd into directories with `z <path_to_dir>`. 
 
Today, I ran `zinit self-update` and now I'm getting the following error when running `z <path_to_dir>`:

```
zsh: command not found: z
```

Relevant snippets of my `.zshrc`:

```zsh
# skywind3000/z.lua
function _z() { _zlua "$@"; }

# Zinit
ZINIT_HOME="${ZDOTDIR}/.zinit"

if [[ -f ${ZINIT_HOME}/bin/zinit.zsh ]] ; then
  source ${ZINIT_HOME}/bin/zinit.zsh
  autoload -Uz _zinit
else
  echo "Installing Zinit..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
fi
zinit light skywind3000/z.lua
```

Reverting to an old snapshot prior to running `zinit self-update` solves the issue.

---

**To Reproduce**

1. Use the above in `.zshrc`
2. Update `zinit` with `zinit self-update`
3. Try to cd into a directory with `z <path_to_dir>`
4. The following error appears: `zsh: command not found: z`

---

**Expected behavior**

`z <path_to_dir>` function should still work after updating `zinit`.

---

**Screenshots**

Commits I updated to when running `zinit self-update`:
![zinit](https://user-images.githubusercontent.com/59181811/81477493-528c0580-9218-11ea-8c8a-8f0ca8bb658e.png)

---

**Versions:**

 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): `Linux archlinux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux`

**Comment by Keysuke** [comment]
My aliases stopped working with the latest commit:
[https://github.com/zdharma/zinit/commit/0f81a7684d5c052dbd8adb35112d70ae458c85d5](https://github.com/zdharma/zinit/commit/0f81a7684d5c052dbd8adb35112d70ae458c85d5)

**Comment by vtnpp** [comment]
Indeed, all my aliases are no longer working either. I didn't think about trying some of them.

**Comment by psprint** [comment]
I've fixed the problem. Thanks for the quick report!

**Comment by psprint** [comment]
I've fixed the problem. Thanks for the quick report!

**Comment by vtnpp** [comment]
Can confirm it's fixed now. Thank you @psprint!
