### ISSUE TITLE
Loading completion script with snippet doesn't work

### ISSUE THREAD

**Issue by hrai** [zdharma/zinit#332]
**Describe the bug**
Loading completion script for `exa` with snippets doesn't load the completions for that script.

**To Reproduce**
Steps to reproduce the behavior.

```
zinit ice as"completion"
zinit snippet https://github.com/ogham/exa/blob/master/contrib/completions.zsh
```

**Expected behavior**
Completions for exa should work when <Tab> is pressed after `exa ` but it doesn't show the possible values.

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Linux DESKTOP-N1PM98I 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by psprint** [comment]
Load the file as follows:

```zsh
zinit as"completion" mv"c* -> _exa" for https://github.com/ogham/exa/blob/master/contrib/completions.zsh
```

It has to be named with the leading underscore for the `as'completion'` to work.

**Comment by hrai** [comment]
That works perfectly. Thanks :)
