### ISSUE TITLE
Issue with removing z-a-man

### ISSUE THREAD

**Issue by onaforeignshore** [zdharma/zinit#333]
**Describe the bug**
After installing z-a-man extension and then choosing not to use it, I get this error every time the shell starts: `compinit:503: no such file or directory: /Users/user/.config/zsh/.zinit/completions/_zman`

**To Reproduce**
Add zman to `.zshrc`, then remove it from the file and delete the folder in the plugins folder.

**Expected behavior**
There shouldn't be an error

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

**Additional context**
None

**Comment by psprint** [comment]
Run `cclear` command to clear stray completions.

**Comment by onaforeignshore** [comment]
Thanks. That sorted it
