### ISSUE TITLE
Snippet in "Multiple-p10k-configs" wiki page does not work (with solution)

### ISSUE THREAD

**Issue by narze** [zdharma/zinit#335]
**Describe the bug**
I tried the snippets in [this page](http://zdharma.org/zinit/wiki/Multiple-p10k-configs/) and found that it don't work. I think it was typo. But don't know what to contribute to the wiki so I decided to post the issue here.

**To Reproduce**
Paste the snipped into ~/.zshrc
```shell
# Load within zshrc – for the instant prompt
zinit atload'!source ~/.p10k.zsh' lucid nocd 
zinit load romkatv/powerlevel10k

[redacted]
```

It prints the error on shell load
```
Error: No plugin or snippet ID given(the last recognized ice was: nocd'').
You can try to prepend `@' if the last ice is in fact a plugin.
```

**Expected behavior**
The line 
```
zinit atload'!source ~/.p10k.zsh' lucid nocd
```
is missing the `ice`.
It should be 
```
zinit ice atload'!source ~/.p10k.zsh' lucid nocd
```

**Screenshots**
-

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): 19.4.0 Darwin (macOS Catalina)

**Additional context**
-

**Comment by psprint** [comment]
It is fixed, thanks.
