### ISSUE TITLE
`ziextract `is unable to extract zipped types `zip/deb/tgz`

### ISSUE THREAD

**Issue by hrai** [zdharma/zinit#340]
**Describe the bug**
`ziextract `is unable to extract zipped types `zip/deb/tgz`

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
It used to work fine. Then when I added a package installation script, it couldn't extract that. Then I removed all the packages and resource `.zshrc`. In the process, `zinit` was unable to extract any of the zipped files. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4055444/82392833-2c702c00-9a88-11ea-8cb7-c7ebafb961c1.png)

![image](https://user-images.githubusercontent.com/4055444/82392863-3f82fc00-9a88-11ea-8ed4-6e931806f707.png)

![image](https://user-images.githubusercontent.com/4055444/82392926-67725f80-9a88-11ea-97bb-c27e48e2b1ac.png)

**Versions:**
 - $ZSH_VERSION == 5,8
 - Operating system name and version (uname -a): Operating system name and version (uname -a): Linux 4.4.0-19613-Microsoft #1000-Microsoft Thu Apr 17 15:57:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by hrai** [comment]
I ran `where ziextract` and found an if condition with below script.

`typeset -f + -- →zinit-extract`

I ran it and get the following output `--`

![image](https://user-images.githubusercontent.com/4055444/82403867-394e4900-9aa3-11ea-8454-f5b707626ab2.png)

**Comment by hrai** [comment]
I downloaded the latest master commit and it's resolved now. Thanks :smiley:

**Comment by psprint** [comment]
Yes, it's fixed, thanks.
