### ISSUE TITLE
Slow loading snippet `kubectl`

### ISSUE THREAD

**Issue by chhschou** [zdharma/zinit#348]
**Describe the bug**
I added `kubectl` as a snippet and immediately my prompt takes about 5 seconds to load, it was near instant before adding the snippet

**To Reproduce**
zinit ice lucid wait'1' id-as'kubectl' as"null" sbin"kubectl"
zinit snippet https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

**Expected behavior**
Expect prompt to appear quickly

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): 5.6.11-1 manjaro

Happy to provide whatever information you need.

**Comment by pschmitt** [comment]
Well. You are doing a web request every time you spawn a shell... Replace the curl portion with a fixed version string.

**Comment by chhschou** [comment]
Makes sense, thanks for looking into this.

**Comment by psprint** [comment]
Yes, that's the reason.
