### ISSUE TITLE
Support multiple 'has' ices for a plugin

### ISSUE THREAD

**Issue by korrat** [zdharma/zinit#351]
I'm using the `for` syntax to install completions and functions for some binaries which were installed through other means. In one case, the binary has a dependency on `fzf`. I would like to encode both dependencies into my `zinit` invocation like so:

```zsh
zinit id-as'fw-setup' has'fw' has'fzf' at-clone'fw-print-zsh-setup --with-fzf > fw-setup.zsh' pick'fw-setup.zsh' for zdharma/null
```
Currently, this does not work. I would like this to only clone/load the plugin if both commands are available.

I can work around this by using the `if` ice and checking the presence of both commands myself, however, I think using multiple `has ` ices would be cleaner.

**Comment by psprint** [comment]
It is implemented, thanks.

**Comment by korrat** [comment]
It works! Awesome, thank you!
