### ISSUE TITLE
[Question] New global git warning when updating zinit and plugins

### ISSUE THREAD

**Issue by vtnpp** [zdharma/zinit#355]
Since I updated `git` to 2.27.0-1 on Arch Linux, every time I run `zinit self-update && zinit update -p --all` I'm met with the following message [(source)](https://public-inbox.org/git/20200304022931.2469455-1-alexhenrie24@gmail.com/):

```
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.
```

and the update is run without issue after this.

Note that I'm getting the same message whenever I run `git pull` from any git repository so it's not specific to zinit. I'm not sure what I'm supposed to do.

What would be the best choice between `--rebase` ; `--no-rebase` and `ff-only`? would it cause any harm for other repositories if I use the  `--global` option?

Please advice.

Thanks.

**Comment by MunifTanjim** [comment]
This change is recently introduced in git.

zinit should change these lines to include `--ff-only` flag:

https://github.com/zdharma/zinit/blob/aab80107512ea2b4f2a9c28d69017d2076347248/zinit-autoload.zsh#L727

https://github.com/zdharma/zinit/blob/aab80107512ea2b4f2a9c28d69017d2076347248/zinit-autoload.zsh#LL729
 
https://github.com/zdharma/zinit/blob/aab80107512ea2b4f2a9c28d69017d2076347248/zinit-autoload.zsh#L1639

https://github.com/zdharma/zinit/blob/aab80107512ea2b4f2a9c28d69017d2076347248/zinit-autoload.zsh#L1650

https://github.com/zdharma/zinit/blob/aab80107512ea2b4f2a9c28d69017d2076347248/zinit-autoload.zsh#L1652

**Comment by MunifTanjim** [comment]
> What would be the best choice between --rebase ; --no-rebase and ff-only? would it cause any harm for other repositories if I use the --global option?

As for what you should do, read this:

> Often novice Git users forget to say "pull --rebase" and end up with an
unnecessary merge from upstream. What they usually want is either "pull
--rebase" in the simpler cases, or "pull --ff-only" to update the copy
of main integration branches, and rebase their work separately. The
pull.rebase configuration variable exists to help them in the simpler
cases, but there is no mechanism to make these users aware of it.
__ quoted from https://public-inbox.org/git/20200304022931.2469455-1-alexhenrie24@gmail.com/

**Comment by psprint** [comment]
The issue should be fixed.

**Comment by vtnpp** [comment]
Can confirm I'm no longer getting the git warning without any `[Pull]` setting in my git config file thanks to 421c0b0.

`zinit self-update && zinit update -p --all`:

```
From https://github.com/zdharma/zinit
 * branch            master     -> FETCH_HEAD
Already up to date.
Compiling Zinit (zcompile)...
Reloading Zinit for the current session...
Updating Zinit...
Parallel Update Starts Now...
Spawning the next 15 concurrent update jobs (plugins)...
The update took 3.35 seconds
```

Thanks.
