### ISSUE TITLE
Parallel update doesn't update snippets from z-a-as-monitor

### ISSUE THREAD

**Issue by Gerrit-K** [zdharma/zinit#360]
**Describe the bug**
Similarly to #350 the command `zi update -p` doesn't update snippets that were added using the `z-a-as-monitor` annex, in my specific case `pulumi` and `terraform`.

**To Reproduce**
```bash
# install the plugins / snippets
zi light zinit-zsh/z-a-as-monitor

zi wait'0a' lucid for \
 if'zi status zinit-zsh/z-a-as-monitor' \
 id-as'terraform' \
 as'monitor|command' \
 atclone'zpextract terraform zip' \
 atpull'%atclone' \
 dlink0'/terraform/%VERSION%/' \
 dlink='/terraform/%VERSION%/terraform_%VERSION%_linux_amd64.zip' \
 is-snippet \
    sbin http://releases.hashicorp.com/terraform/ \
 if'zi status zinit-zsh/z-a-as-monitor' \
 id-as'pulumi' \
 as'monitor|command' \
 atclone'ziextract --auto && mv pulumi pulumi-bin && mv pulumi-bin/* ./ && rm -rf pulumi-bin' \
 atpull'%atclone' \
 dlink='https://get.pulumi.com/releases/sdk/pulumi-%VERSION%-linux-x64.tar.gz' \
    sbin'pulumi*' https://www.pulumi.com/docs/get-started/install/versions/ \

# making zinit believe that the version is outdated
zi run terraform rm './._zinit/url_rsvd'
zi run pulumi rm './._zinit/url_rsvd'

# update isolated:
zi update terraform # pulumi analogously
# as-monitor annex: Matched the following URL: http://releases.hashicorp.com/terraform/0.13.0-beta1/terraform_0.13.0-beta1_linux_amd64.zip
# 
# Updating snippet terraform... (identified as: terraform)
# Downloading `terraform' (with curl, wget, lftp)...
# ################################################################################################################################# 100.0%
# ziextract: Unpacking the files from: `terraform'...
# Archive:  terraform
#   inflating: terraform
# ziextract: Successfully extracted and assigned +x chmod to the file: `terraform'.

# update with -p
zi update -p
# Updating Zinit...
# Parallel Update Starts Now...
# Spawning the next 15 concurrent update jobs (snippets)...
# Spawning the next 15 concurrent update jobs (plugins)...
# Spawning the next 15 concurrent update jobs (plugins)...
# The update took 9.70 seconds
# -> none of the two plugins were updated
```

**Comment by psprint** [comment]
The issue has been fixed, thanks.

**Comment by psprint** [comment]
BTW., you can check out a minimized pulumi example on [z-a-as-monitor](https://github.com/zinit-zsh/z-a-as-monitor/#other-examples) page.

**Comment by Gerrit-K** [comment]
Thanks for the tip! Unfortunately I couldn't confirm that it works now, since neither both examples nor my old configuration seems to work after updating zinit and the annexes 😕 

This is the output I get for a fresh run (i.e. all folders and binaries removed):
![image](https://user-images.githubusercontent.com/8766565/84573396-7eaf1f00-ada0-11ea-8fdc-1362785b8598.png)

PS: The windows example in the zinit readme contains backticks instead of single quotes. Not sure if that's intentional / works on windows, but it definitely could cause problems for *nix users that copy & paste the snippet and simply adjust the url 😉

**Comment by psprint** [comment]
That is really weird. Could you post your Zinit command? The following works for me without problems:

```zsh
zi id-as'pulumi' as'monitor|null' mv'pulumi pulumi_' extract'!!' \
    dlink='https://get.pulumi.com/releases/sdk/pulumi-%VERSION%-windows-x64.zip' \
    sbin'pulumi*' for \
        https://www.pulumi.com/docs/get-started/install/versions/ \
```

**Comment by Gerrit-K** [comment]
Currently my command is:
```bash
zi light zinit-zsh/z-a-as-monitor

zi wait'0a' lucid for \
... (some other plugins)
 id-as'pulumi' \
 as'monitor|null' \
 mv'pulumi pulumi_' \
 extract'!!' \
 dlink='https://get.pulumi.com/releases/sdk/pulumi-%VERSION%-linux-x64.tar.gz' \
    sbin'pulumi*' https://www.pulumi.com/docs/get-started/install/versions/ \
```

This resulted in:
![image](https://user-images.githubusercontent.com/8766565/85102455-02379880-b205-11ea-848c-dc2097cbefc5.png)

Just to be sure, I've also tested this to eradicate potential side effects:
```bash
zi light zinit-zsh/z-a-as-monitor

zi \
 id-as'pulumi' \
 as'monitor|null' \
 mv'pulumi pulumi_' \
 extract'!!' \
 dlink='https://get.pulumi.com/releases/sdk/pulumi-%VERSION%-linux-x64.tar.gz' \
 sbin'pulumi*' \
    for https://www.pulumi.com/docs/get-started/install/versions/
```

But it results in the same error.

This is for `zsh 5.8.0.2-dev (x86_64-pc-linux-gnu)` (recently compiled) and zinit@ 16c08431
I've also tested a previous commit (f2150825) but still the same error appeared. If you want, I can try to git bisect the issue, but it'll take some time 😕

**Comment by psprint** [comment]
Change `extract'!!'` to `extract'!'` and it will work.

**Comment by Gerrit-K** [comment]
It does, thanks! (and sorry for the late reply)
