### ISSUE TITLE
Errors when using the Minimal Setup example

### ISSUE THREAD

**Issue by rdemetrescu** [zdharma/zinit#365]
**Describe the bug**
Following the example described at https://zdharma.org/zinit/wiki/Example-Minimal-Setup/ and running it for the first time give us 2 errors

**To Reproduce**
After the zinit installer code at `~/.zshrc` add the setup described at the above URL:

```zshrc
zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
      zdharma/fast-syntax-highlighting \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zinit light zsh-users/zsh-completions
```
 then remove any previous created `~/.zinit` folder and start a new zsh session.

You will see the following errors, during automatic zinit setup:

```
Downloading zinit... (as zinit...)

Cloning into '/home/roger/.zinit/plugins/zinit'...
remote: Not Found
fatal: repository 'https://github.com/zinit/' not found

No such (plugin or snippet) directory: zinit

Downloading light... (as light...)

Cloning into '/home/roger/.zinit/plugins/light'...
remote: Not Found
fatal: repository 'https://github.com/light/' not found

No such (plugin or snippet) directory: light
```

Also, when running `zinit loaded` you get this result:

```
zdharma/fast-syntax-highlighting *
zsh-users/zsh-autosuggestions *
zinit *
light *
zsh-users/zsh-completions *
```
as if `zinit` and `light` were plugins.

**Expected behavior**
No errors (red color) during first run and the following result when running `zinit loaded`:

```
zdharma/fast-syntax-highlighting *
zsh-users/zsh-autosuggestions *
zsh-users/zsh-completions *
```

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Linux ohm 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Fix suggestion**
Remove the `zinit light` expression from the minimal example setup:

```
zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
      zdharma/fast-syntax-highlighting \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions
```

**Comment by psprint** [comment]
It is done, thanks.
