### ISSUE TITLE
docker and docker-compose completion not working

### ISSUE THREAD

**Issue by fauust** [zdharma/zinit#367]
**Describe the bug**
I am unable to make docker and docker-compose completion to work.

**To Reproduce**
```console
zinit ice as"completion"
zinit snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
zinit ice as"completion"
zinit snippet https://github.com/docker/compose/tree/master/contrib/completion/zsh/_docker-compose
```
**Expected behavior**
docker and docker-compose completion works

**Versions:**
```console
❯ zsh --version
zsh 5.7.1 (x86_64-debian-linux-gnu)
~
❯ uname -a
Linux laptop 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```

**Other information**

I have tried to disable everything else and I removed `.zcompdump` file.

Also, the following completion is working:
```console
zinit ice as"completion"
zinit snippet https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fd/_fd
```

**Comment by psprint** [comment]
What does the following say?

```
zinit cenable docker
```
?

**Comment by fauust** [comment]
```console
❯ zinit cenable docker
Completion docker already enabled
❯ zinit clist | grep docker
100.0%
docker-compose                      %SNIPPETS/https--github.com--docker--compose--tree--master--contrib--completion--zsh/_docker-compose
docker                              %SNIPPETS/https--github.com--docker--cli--blob--master--contrib--completion--zsh/_docker
❯ zinit csearch | grep docker
```

**Comment by psprint** [comment]
This is then weird. The completion should work. It does on my machine.

sob., 27 cze 2020, 10:31 użytkownik faust <notifications@github.com>
napisał:

**Comment by fauust** [comment]
Ok then I am going to try to make it work in a totally clean environment...

**Comment by davidosomething** [comment]
works for me too 
```
zinit lucid has'docker' for \
  as'completion' is-snippet \
  'https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker' \
  \
  as'completion' is-snippet \
  'https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose' \

```

**Comment by fauust** [comment]
Ok, problem identified:
https://github.com/garabik/grc/issues/93

This may mean something to you and also https://github.com/garabik/grc/pull/84. Anyway, I have disabled grc for docker and docker-compose commands.

Thanks for your help and this great project!

**Comment by psprint** [comment]
Great :)
