### ISSUE TITLE
Apply personal patch to plugin during clone and pull?

### ISSUE THREAD

**Issue by dylanjm** [zdharma/zinit#368]
**Is your feature request related to a problem? Please describe.**

Not sure if this is a bug or a feature. But I have a patch that removes calls to `compinit` in a package and would like to be able to apply this patch anytime I update or when bootstrapping my shell. But when trying to do so, the plugin is not cloned at all and seems to be skipped. 

**Describe the solution you'd like**

Currently my solution is:

```
zinit ice wait lucid ver"dev" \
      atclone"patch -i $ZSH/zcomp.patch" \
      atpull'!git clean -dfx' run-atpull'%atclone' \
zinit light marlonrichert/zsh-autocomplete
```

**Comment by psprint** [comment]
This task is being done by the [z-a-patch-dl](https://github.com/zinit-zsh/z-a-patch-dl) annex.

**Comment by psprint** [comment]
BTW you can also use subst'A -> B' ice.
