### ISSUE TITLE
Can not install cheat.sh correctly (filename contained special character)

### ISSUE THREAD

**Issue by kirintwn** [zdharma/zinit#369]
**Describe the bug**

According to [cheat.sh installation guide](https://github.com/chubin/cheat.sh#installation)
the installation of `cheat.sh` is download a `:cht.sh` file, rename it to `cht.sh`, `chmod +x` it, and add it to $PATH.

I have tried to install it via zinit with the following:
```bash
zinit ice as"program" mv"*cht.sh -> cht.sh" pick"cht.sh"
zinit snippet "https://cht.sh/:cht.sh"
```

The result will be:
```bash
Setting up snippet           cht.sh/:cht.sh
Downloading `cht.sh/:cht.sh' (with curl, wget, lftp)...
######################################################################## 100.0%
:cht.sh -> cht.sh

$ which cht.sh
cht.sh not found
# (Not working)

$ /Users/username/.zinit/snippets/https--cht.sh/:cht.sh/cht.sh
Usage:
    cht.sh [OPTIONS|QUERY]
...
# (Working)
```

```bash
$ echo $PATH
/Users/username/.zinit/snippets/https--cht.sh/:cht.sh:/usr/local/bin:/usr/bin
```
_Possible Cause: The original file `:cht.sh` contains the character `:`, which will cause zinit add the bin to $PATH incorrectly._

**To Reproduce**

As above.

```bash
zinit ice as"program" mv"*cht.sh -> cht.sh" pick"cht.sh"
zinit snippet "https://cht.sh/:cht.sh"
```

```bash
$ which cht.sh
```

**Expected behavior**

```
$ which cht.sh
/Users/username/.zinit/snippets/https--cht.sh/:cht.sh/cht.sh
```

**Comment by psprint** [comment]
Could you check `print -rl $path`? The path element should be added correctly there.

As a workaround, I would recommend utilizing `sbin''` ice of the bin-gem-node annex:

```zsh
zinit ice mv"*cht.sh -> cht.sh" sbin"cht.sh"
zinit snippet "https://cht.sh/:cht.sh"
```

**Comment by kirintwn** [comment]
Thanks for the reply, I completely uninstall `cht.sh` and try to  re-install today.

Somehow the $path is added correctly, and it works without any problems. I cannot reproduce the problem again.

Maybe it was because I did not prune previous incorrect installation completely.

Thanks.

**Comment by BirkhoffLee** [comment]
fyi this works on my machine:

```shell
zinit light-mode for \
  as"program" id-as"cht.sh" \
    @https://cht.sh/:cht.sh \
  as'completion' id-as"_cht.sh" \
    @https://cht.sh/:zsh
```
