### ISSUE TITLE
Git repos created for typos, causing 'zinit update' 404s

### ISSUE THREAD

**Issue by GaryBoone** [zdharma/zinit#370]
**Describe the bug**
Plugins/Snippets/etc create repos in .zinit/ by name. The name can be wrong due to typos or keyword errors in .zinitrc. But after fixing the error in .zinitrc, the repo remains. Then 'zinit update' generates 404 errors as it tries to update erroneous repos.

**To Reproduce**
Steps to reproduce the behavior.

1. Edit .zinitrc and add: 
    zinit wait lucid for OMZL::colored-man-pages

2. Restart zinit:
Setting up snippet           OMZL::colored-man-pages
Downloading `OMZL::colored-man-pages' (with curl, wget, lftp)...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
ERROR: Download failed.

3. Ok, that was wrong. It's a plugin. Edit .zinitrc and change to: 
    zinit wait lucid for OMZP::plugins/colored-man-pages

4. Restart zinit:
Snippet not loaded (OMZP::plugins/colored-man-pages)

5. Oh, that was also wrong. Don't need the 'plugin/' directory. Edit .zinitrc and change to: 
    zinit wait lucid for OMZP::colored-man-pages

6. Restart zinit:

Setting up snippet           OMZP::colored-man-pages
Downloading `OMZP::colored-man-pages' (with curl, wget, lftp)...
######################################################################## 100.0%

7. Success. Now try updating.
$ zinit update
...
Updating snippet OMZ::plugins/colored-man-pages
Downloading `OMZ::plugins/colored-man-pages' (with curl, wget, lftp)...
##################################################################################################################################### 100.0%
...
Updating snippet OMZL::colored-man-pages
Downloading `OMZL::colored-man-pages' (with curl, wget, lftp)...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
ERROR: Download failed.
...
Updating snippet OMZP::colored-man-pages
Downloading `OMZP::colored-man-pages' (with curl, wget, lftp)...
##################################################################################################################################### 100.0%
...
Updating snippet OMZP::plugins/colored-man-pages
Downloading `OMZP::plugins/colored-man-pages' (with curl, wget, lftp)...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
ERROR: Download failed.

8. Whoa. Two problems: 
• It updated OMZP::colored-man-pages twice! Once as 'OMZP::colored-man-pages' and once as 'OMZ::plugins/colored-man-pages'
• It update the two repos based on wrong names, 'OMZL::colored-man-pages' and 'OMZP::plugins/colored-man-pages', failing both times.

**Expected behavior**
• Zinit should not create repos for typos or other errors. 
• Zinit should not include erroneous repos when updating

**Versions:**
 - $ZSH_VERSION == .5.8
 - Operating system name and version (uname -a): Darwin Kernel Version 19.5.0

**Comment by GaryBoone** [comment]
Notes:
• A related problem is that the git repos aren't culled when they're no longer used in the .initrc. Users will see monotonically growing update times as obsolete, unused git repos continue to be updated.

• It appears that a simple way to resync the repos to the correct set is to just delete the directories under `.zinit/plugins`. The repos matching the current .zshrc, without the extras, will be redownloaded the next time zinit starts.

**Comment by GaryBoone** [comment]
• The same problem occurs for OMZL libraries. In my .zshrc file, I have:
```
    zinit wait lucid for OMZL::directories.zsh
```
In the `$ zinit update` output, I see:
```
Updating snippet OMZ::directories.zsh
Downloading `OMZ::directories.zsh' (with curl, wget, lftp)...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
ERROR: Download failed.
...
Updating snippet OMZL::directories.zsh
Downloading `OMZL::directories.zsh' (with curl, wget, lftp)...
##################################################################################################################################### 100.0%
```

So a fail with one variation of the name, `OMZ::directories.zsh'`, then a success with another, `OMZL::directories.zsh`.

**Comment by GaryBoone** [comment]
Where are the repos for the OMZ* plugins stored?

**Comment by psprint** [comment]
The snippets are stored in `~/.zinit/snippets`. The issue is now resolved for them. PS. You can delete any snippet by `zi delete {id}`.

**Comment by GaryBoone** [comment]
Success! Thanks, Sebastian.

Re OMZ* snippets, I see. They're not git repos. This explains why I see them downloaded each time I do a `zi update`.
