### ISSUE TITLE
install.sh doesn't honor the new ZINIT hash array locations

### ISSUE THREAD

**Issue by syntaxman** [zdharma/zinit#371]
**Describe the bug**
The install.sh file described in the README for installation still uses the string variable names instead of the new ZINIT hash array.  If a user creates and exports those values before running the install.sh script, the installation will still all be in the default ~/.zinit directory.  In reading the install.sh script, I saw that the script is intended to look for envvars that will define the locations to use, but they were the old string variables, not the ZINIT variables that replaced them.

**To Reproduce**
Set all desired values for the ZINIT hash array, as described in the README under Hints and Tips : Customizing Paths.  Source/export these variables, then run the doc/install.sh script.  All files are still installed to the default locations.

**Expected behavior**
I expected the install.sh script to place the files according to the values in the ZINIT hash array.

**Screenshots**

**Versions:**
 - $ZSH_VERSION == zsh 5.8 (x86_64-pc-linux-gnu)
 - Operating system name and version (uname -a): Linux lexeme 5.7.5-arch1-1 #1 SMP PREEMPT Mon, 22 Jun 2020 08:10:02 +0000 x86_64 GNU/Linux

**Comment by psprint** [comment]
The script uses `ZPLG_HOME` as `/bin/sh` doesn't support hashes and also they cannot be exported.

**Comment by syntaxman** [comment]
Oh... I see.  It does reference the old string vars, but falls back on ZPLG_HOME.  I hadn't noticed that you can't export hashes because I exported each one on the same line it was defined.  Zsh didn't throw an error.  Anyway, thank you for looking at the issue.
