### ISSUE TITLE
Can't automate 'zi delete --clean' with 'yes'

### ISSUE THREAD

**Issue by GaryBoone** [zdharma/zinit#372]
**Describe the bug**
`$ yes | zi delete --clean` should automatically perform the requested action without user interaction. But the interactive prompt is shown and progress halts. `/usr/bin/yes` is a standard utility in Linux and Mac that allows automation of scripts with y/n type prompts.

This issue could also be a feature request for an additional flag to not require a confirmation, such as `$ zi delete --clean --yes`. Purpose: As a user, I would like to include the clean function in a script that updates and cleans my zinit installation.

**To Reproduce**
```
$ yes | zi delete --clean
Prune CURRENTLY NOT LOADED plugins in [...]/.zinit/plugins and snippets in [...]/.zinit/snippets?
[yY/n…]
```

**Expected behavior**
```
$ yes | zi delete --clean
Deleting the following 0 UNLOADED snippets:
Done (with the exit code: 0).

Deleting the following 0 UNLOADED plugins:
Done (with the exit code: 0).

Done (action executed, exit code: 0)
```

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Darwin Kernel Version 19.5.0

**Comment by psprint** [comment]
You can use `--yes` with `delete`.

**Comment by psprint** [comment]
I've extended `delete` so that it works with `yes` too.
