### ISSUE TITLE
command not found: sleep

### ISSUE THREAD

**Issue by aka-luan** [zdharma/zinit#375]
I'm receveing this message everytime I open hyper terminal and don't know how to procede

![image](https://user-images.githubusercontent.com/42617945/86478632-e9f56c80-bd20-11ea-847a-071bb9cdfb13.png)

**Comment by psprint** [comment]
you could do `print '#!/usr/bin/zsh\n:' > /usr/local/bin/sleep` or install a `sleep` command.
