### ISSUE TITLE
pmodload crashes as of 2a1a6ae45c6bd411135db61c488f7ea7bdfc8b31

### ISSUE THREAD

**Issue by NorthIsUp** [zdharma/zinit#381]
**Describe the bug**
`pmodload` fails when running.

```
$ pmodload
+> pmodload
+> local -A ices
+> ices=( '' teleid '' ) pmodload:2: bad set of key/value pairs for associative array
```

**To Reproduce**
run pmodload

**Expected behavior**
It should not crash :)

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Additional context**
2a1a6ae45c6bd411135db61c488f7ea7bdfc8b31 seems to be the breaking change.

**Comment by psprint** [comment]
It should be fixed now, thanks!
