### ISSUE TITLE
ERROR: The source snippet file doesn't exist.

### ISSUE THREAD

**Issue by rhuang2014** [zdharma/zinit#382]
**Describe the bug**
Setting up snippet: zsh/_docker
ERROR: The source file docker/cli/blob/master/contrib/completion/zsh/_docker doesn't exist.
Copying _docker...
cp: docker/cli/blob/master/contrib/completion/zsh/_docker: No such file or directory
ERROR: The file copying has been unsuccessful.

**To Reproduce**
`zinit ice as"completion"; zinit snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker`

**Expected behavior**
zinit commands to work

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - uname -a == Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

**Additional context**
Ran `zinit self-update && zinit update -r` then got the error.

**Comment by dotrakoun-sqsp** [comment]
able to reproduce
```
zinit lucid has'docker' for \
  as'completion' is-snippet \
  'https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker' \
  \
  as'completion' is-snippet \
  'https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose' \
```

**Comment by psprint** [comment]
It's fixed, thanks.

**Comment by rhuang2014** [comment]
Thanks. works.
