### ISSUE TITLE
Zinit update pipes to a pager, preventing scripted updates from completing

### ISSUE THREAD

**Issue by GaryBoone** [zdharma/zinit#383]
**Describe the bug**
I'm trying to include `zinit self-update` and `zinit update` in a shell script. During the update, Zinit pipes the update notes or git log to a pager like `more` or `less`. As a result, the script stops, waiting for user input, if there are many updates. Hitting `q` exits the pager and the the update continues. This forced interactivity means that the script can't run to completion automatically. 

**To Reproduce**
`$ zinit self-update` or `$ zinit update` after there have been many updates. There have to be enough that the pager will pause the output so that the user can enter a command.

**Expected behavior**
The updates should run to completion without requiring user interaction.

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Darwin Kernel Version 19.5.0

**Comment by chulkilee** [comment]
Just hit this issue.

- `--quiet` option does not disable pager
- `export GIT_PAGER=cat` does not work

Probably because zinit uses `.zinit-pager` function?

**Comment by psprint** [comment]
I've added the `-n/--no-pager` option to `update`. You can use it to disable the pager.
