### ISSUE TITLE
Plugin compilation and completion triggered twice on update

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#398]
**Describe the bug**
Whenever a plugin is updated, it's compiled and completions are installed. However, it seems this process occurs twice as in the log two messages are printed for each of these actions.

**To Reproduce**
I tested this with the `zinit update -p 16` command. I'm not sure if it occurs with the normal serial update process. Simply update and view the message. Compiling and completion messages will show up twice.

**Expected behavior**
These occur once.

**Screenshots**
![image](https://user-images.githubusercontent.com/15698885/89492402-81fecf80-d77f-11ea-8388-685bcac0442b.png)

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Linux Nicks-Laptop 5.7.0-12.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.7-17.1~bullseye (2020-07-31) x86_64 GNU/Linux`

**Comment by davidosomething** [comment]
The more times you update in a shell session, the more times it will do it!

**Comment by psprint** [comment]
I've fixed the issue, thanks.
