### ISSUE TITLE
(eval):ZpluginModule_:1: can't write zwc file: /proc/self/fd/13.zwc

### ISSUE THREAD

**Issue by chhschou** [zdharma/zinit#406]
**Describe the bug**
`(eval):ZpluginModule_:1: can't write zwc file: /proc/self/fd/13.zwc` appears before prompt is loaded on a new terminal and sometime after subshell exec.

**To Reproduce**
install starship prompt 
add `eval $(starship init zsh)` to end of .zshrc

**Expected behavior**
No message displayed

**Screenshots**
![Screenshot from 2020-08-28 23-31-07](https://user-images.githubusercontent.com/429067/91556297-9e5ce900-e986-11ea-9ffa-2a20c4f9341c.png)

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): manjaro 5.7

**Additional context**
`echo $(starship zsh init)` gets
```
source <("/home/chhschou/.asdf/installs/rust/stable/bin/starship" init zsh --print-full-init)

```
I think the `source` is the issue here. maybe related to #104 but this is specific to linux, same code runs fine on macos catalina

**Comment by solarizedalias** [comment]
Assumimg the line is literally what you have in .zshrc, you should at least double quote the command substitution. I had a similar issue with starship init in the past and it has gone after quoted.

```zsh
$ eval "$(starship init zsh)"

# Without the quote, the lines split like this.
$ f() { print -rl -- $@; }
$ f $(starship zsh init)
source
<("/usr/local/bin/starship"
init
zsh
--print-full-init)

$

```

**Comment by chhschou** [comment]
@solarizedalias my apologies, I do have it as `eval "$(starship init zsh)"` in .zshrc file

**Comment by psicho2000** [comment]
I am experiencing the exact same problems. The cause is that zinit modules are loaded before starship is initialized.

If I change the loading order so that starship loads before zinit modules, it works fine:
```
eval "$(starship init zsh)"

module_path+=( "/home/ubuntu/.zinit/bin/zmodules/Src" )
zmodload zdharma/zplugin
```

**Comment by chhschou** [comment]
I just silent the error with
```
# starship prompt
eval "$(starship init zsh)" > /dev/null 2>&1
```
