### ISSUE TITLE
zinit downloads all plugins for the second time to a wrong directory after  new zsh session pops up

### ISSUE THREAD

**Issue by dwemerx** [zdharma/zinit#407]
**Describe the bug**
When I open terminal, zinit reads data from .config/zsh/zinit, but when I open new session inside current one (say by launching tmux), zinit reads data from .config/zsh/.zinit

.zprofile
```
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export ZINIT[BIN_DIR]="$ZDOTDIR/zinit/bin"
export ZINIT[HOME_DIR]="$ZDOTDIR/zinit"
export ZINIT[PLUGINS_DIR]="$ZDOTDIR/zinit/plugins"
export ZINIT[COMPLETIONS_DIR]="$ZDOTDIR/zinit/completions"
export ZINIT[SNIPPETS_DIR]="$ZDOTDIR/zinit/snippets"
export ZINIT[ZCOMPDUMP_PATH]="$ZDOTDIR/zinit/.zcompdump"
export ZPFX="$ZDOTDIR/zinit/polaris"
```

.zshrc
```
zinit load chrissicool/zsh-256color
zinit load supercrabtree/k
zinit load hlissner/zsh-autopair

zinit load djui/alias-tips
export ZSH_PLUGINS_ALIAS_TIPS_FORCE=1

# syntax highlights
zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
    zsh-users/zsh-history-substring-search \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions

# theme
zinit snippet OMZT::nicoulaj
```

**To Reproduce**
1. Install zsh
2. Add the content above to appropriate files
3. Launch terminal and see expected behavior
4. Launch zsh or tmux and see unexpected behavior

**Expected behavior**
zinit always reads data from .config/zsh/zinit

**Screenshots**
[![asciicast](https://asciinema.org/a/O1L5MaIaypQYlI7cs7CXjr3Wg.svg)](https://asciinema.org/a/O1L5MaIaypQYlI7cs7CXjr3Wg)

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Linux vm 4.19.128-1.pvops.qubes.x86_64 #1 SMP Sun Jun 28 06:19:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by psprint** [comment]
The exports will not work -- it's not possible to export hashes. You gonna
have to set the variables in zshrc.

**Comment by dwemerx** [comment]
Ah, moving ZINIT declaration and exports to .zshrc fixed the issue. Thank you!
