### ISSUE TITLE
Support custom url of OMZ, PZT etc.

### ISSUE THREAD

**Issue by winnochan** [zdharma/zinit#410]
**Is your feature request related to a problem? Please describe.**
The download speed from github repo is too slow. I have made some mirror repos to gitee from China. But I have no solution to custom set the mirror url to OMZ variable.

**Describe the solution you'd like**
I want to set the custom url of OMZ, PZT etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by psprint** [comment]
You can do it by setting the fields in the associative arrays `$ZINIT_1MAP` and `$ZINIT_2MAP`.
