### ISSUE TITLE
tput might not be available

### ISSUE THREAD

**Issue by davidosomething** [zdharma/zinit#411]
As stated in line https://github.com/zdharma/zinit/blob/2110fe9815e78ef79bb6dbdb0b57beaf64d46eff/git-process-output.zsh#L24
zinit may be running on systems without tput.

So the tput on line 7
https://github.com/zdharma/zinit/blob/2110fe9815e78ef79bb6dbdb0b57beaf64d46eff/git-process-output.zsh#L7
should be silenced (or an alternative used)

Ran across this because I'm using in a busybox without tput

**Comment by psprint** [comment]
It is done, thanks.
