### ISSUE TITLE
silent and lucid not work when new shell loads first plugins

### ISSUE THREAD

**Issue by octaltree** [zdharma/zinit#418]
**Describe the bug**
I don't want the message "Loaded $___id" so I set my config file like this.
```
zinit ice silent lucid wait'!1'; zinit load _local/sandbox
zinit ice silent lucid wait'!1'; zinit load zsh-users/zsh-syntax-highlighting
zinit ice silent lucid wait'!1'; zinit load zsh-users/zsh-completions
```
But, "Loaded $___id" was shown on new shell.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![Peek](https://user-images.githubusercontent.com/7942952/93837396-e4287b00-fcc0-11ea-8aa7-919be60d1320.gif)
This is value of silent and lucid when zinit is started.
silent and lucid is 1 after "Loaded $___id" having already be shown.
` echo "silent${+ICE[silent]} lucid${+ICE[lucid]}"`
```
    if [[ $___action = *load ]]; then
        if [[ $___tpe = p ]]; then
            .zinit-load "${(@)=___id}" "" "$___mode"; (( ___retval += $? ))
        elif [[ $___tpe = s ]]; then
            .zinit-load-snippet $___opt "$___id"; (( ___retval += $? ))
        elif [[ $___tpe = p1 || $___tpe = s1 ]]; then
            (( ${+functions[.zinit-service]} )) || builtin source "${ZINIT[BIN_DIR]}/zinit-additional.zsh"
            zpty -b "${___id//\//:} / ${ICE[service]}" '.zinit-service '"${(M)___tpe#?}"' "$___mode" "$___id"'
        fi
        echo "silent${+ICE[silent]} lucid${+ICE[lucid]}"
        (( ${+ICE[silent]} == 0 && ${+ICE[lucid]} == 0 && ___retval == 0 )) && zle && zle -M "Loaded $___id"
    elif [[ $___action = *remove ]]; then
```

**Versions:**
 - $ZSH_VERSION == ...
 5.8
 - Operating system name and version (uname -a): ...
  Linux coorie 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux
- tmux
  tmux 3.1b
 - zinit
   284784985

**Additional context**

**Comment by numToStr** [comment]
Try only `lucid`, remove `silent`.

Other way to do the same is
```
zinit wait'1' lucid for \
    _local/sandbox \
    zsh-users/zsh-syntax-highlighting \
    zsh-users/zsh-completions \
```

**Comment by octaltree** [comment]
Thank you very much. I tried only lucid again and it worked.
