### ISSUE TITLE
zstyle commands not working any more

### ISSUE THREAD

**Issue by scalp42** [zdharma/zinit#420]
Hi @psprint 

Thank you so much for the wonderful project!

**Describe the bug**
I switched from zgen and unfortunately `ztyle` commands don't seem to work anymore.

**To Reproduce**

```
source $ZSH_CONF/zinit.zsh

# NOTE: brew install terminal-notifier
zinit ice wait"0" lucid
zinit light marzocchi/zsh-notify

# NOTE: https://github.com/marzocchi/zsh-notify
zstyle ':notify:*' error-title "Command failed (in #{time_elapsed} seconds)"
zstyle ':notify:*' success-title "Command finished (in #{time_elapsed} seconds)"
zstyle ':notify:*' command-complete-timeout 2
zstyle ':notify:*' enable-on-ssh yes
zstyle ':notify:*' blacklist-regex 'find|git|cd|l|ll|ls|cat|bat|man|gti'
```

**Expected behavior**

If I sleep 2 seconds, it should show the prompt (default is 30secs).

If I sleep for 31 seconds, it doesn't show the right message (it should be `Command finished...`):

![image](https://user-images.githubusercontent.com/1475276/95448841-cc840000-0918-11eb-9763-4e38a1881948.png)

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Darwin anthowo.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,3 Darwin`

Thanks in advance 🙏

**Comment by NICHOLAS85** [comment]
The issue is https://github.com/marzocchi/zsh-notify must be configured after it is sourced where as with your current zsh config zstyle is acting before it is sourced. This is because with your `wait` ice, the plugin is loading after your zstyle lines. To fix this you can add those lines to an `atload` ice which will run the zstyle lines after the plugin loads:
```
zinit ice wait"0" lucid atload'
	zstyle ":notify:*" error-title "Command failed (in #{time_elapsed} seconds)"
	zstyle ":notify:*" success-title "Command finished (in #{time_elapsed} seconds)"
	zstyle ":notify:*" command-complete-timeout 2
	zstyle ":notify:*" enable-on-ssh yes
	zstyle ":notify:*" blacklist-regex "find|git|cd|l|ll|ls|cat|bat|man|gti"'
zinit light marzocchi/zsh-notify
```

**Comment by scalp42** [comment]
Closing, it's working. Thanks for the help @NICHOLAS85 🙏
