### ISSUE TITLE
Issue updating plugins using new 'master' -> 'main' github branch naming convention

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#425]
**Describe the bug**
If a plugin's master branch is named main, the plugin will fail to update with `zinit update`. I'm assuming this could occur with other names aswell.

**To Reproduce**
An example repo is https://github.com/marlonrichert/zsh-edit. When this plugin recieves updates the following messages print:
```
fatal: couldn't find remote ref master
fatal: couldn't find remote ref master
```

**Expected behavior**
Plugin to update correctly. Here's a link to the new convention: https://github.com/github/renaming

**Screenshots**
![Screenshot 2020-10-31 19:02:30](https://user-images.githubusercontent.com/15698885/97791706-b2ea7700-1bab-11eb-9e31-2c229dc25f20.png)

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Linux Nicks-Laptop 5.8.0-17.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.8-16.1~bullseye (2020-10-29) x86_64 GNU/Linux`

**Comment by narze** [comment]
I got similar error, but with main ref instead
```shell
Updating ogham/exa
Binary release already up to date (version: v0.9.0)
Updating romkatv/powerlevel10k
2020-11-06 2fc7257 docs
fatal: couldn't find remote ref main
fatal: couldn't find remote ref main
Note: Compiling: powerlevel10k.zsh-theme… OK.
Updating romkatv/zsh-prompt-benchmark
fatal: couldn't find remote ref main
Updating trapd00r/LS_COLORS
fatal: couldn't find remote ref main
Updating zdharma/fast-syntax-highlighting
fatal: couldn't find remote ref main
Updating zdharma/history-search-multi-word
fatal: couldn't find remote ref main
Updating zdharma/null
fatal: couldn't find remote ref main
Updating zinit-zsh/z-a-bin-gem-node
fatal: couldn't find remote ref main
Updating zsh-users/zsh-autosuggestions
fatal: couldn't find remote ref main
Updating zsh-users/zsh-completions
fatal: couldn't find remote ref main
Updating zsh-users/zsh-history-substring-search
fatal: couldn't find remote ref main
```

**Comment by NICHOLAS85** [comment]
That new error is caused from this line:
https://github.com/zdharma/zinit/blob/97f994f4909de67e2be398d5e92faa2d5c160488/zinit-autoload.zsh#L1580
It's not being run in the plugin directory as I believe it should be.

**Comment by narze** [comment]
I see, should it have `command` in the front of `git` like the other lines?

**Comment by AnimiVulpis** [comment]
@narze adding `command` will not fix the problem.
This https://github.com/zdharma/zinit/commit/e45b3d74dbab9c1fda8ba8ca379d6e6f17ea5ba9#r43973927 fixes _part_ of the problem.

But you will end up with the problem explained here: https://github.com/zdharma/zinit/issues/428#issuecomment-724009537

I guess this issue can now be tracked in #428
