### ISSUE TITLE
fatal: not a git repository error when updating any plugins

### ISSUE THREAD

**Issue by eeleater** [zdharma/zinit#428]
**Describe the bug**
When I do zinit update, when it comes to updating the plugins I get the following error:

".fatal: not a git repository (or any of the parent directories): .git"

**To Reproduce**
Not sure, I just do zinit update, and get the error message as seen above

**Expected behavior**
Just update the git repos for the plugins without that error.

**Screenshots**
https://imgur.com/a/cMZIs5m

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux pxm.eeleater.org 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 GNU/Linux

(But this also happens on any of my Systems, be it my work laptop with wsl, my proxmox server, or any of the vms on it)

**Additional context**
If needed, my dotfiles repo: https://git.eeleater.org/eeleater/dotfiles

**Comment by kirintwn** [comment]
Can confirmed it happens on all of my systems including MacOS & Linux.

**Comment by giulianisanches** [comment]
Same here. Ubuntu 20.04 LTS.

Full message bellow

```
~
❯ zinit update --all
Updating Zinit…
Note: updating also unloaded plugins
Updating sindresorhus/pure
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Updating zdharma/fast-syntax-highlighting
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Updating zsh-users/zsh-autosuggestions
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Updating zsh-users/zsh-completions
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
The update took 8.33 seconds

~
❯ 
```

**Comment by yangxyo** [comment]
+1

**Comment by AnimiVulpis** [comment]
I investigated a bit and every commit before e45b3d74 works fine.

Every commit after (including) e45b3d74 has this error (for me).

Haven't yet found a possible culprit.

FYI: Found this commit by running `git bisect` inside of `~/.local/share/zinit/bin`, opening a new console and running `zinit update`

**Comment by AnimiVulpis** [comment]
FYI: Found out that https://github.com/zdharma/zinit/commit/e45b3d74dbab9c1fda8ba8ca379d6e6f17ea5ba9#r43973927 will fix the `fatal` part of the error, but **will result** in being in the folder of the plugin after `zinit update <package>` finishes:

Example:
```
$ zinit update hcgraf/zsh-sudo
<stuff happens>
$ pwd
~/.local/share/zinit/plugins/hcgraf---zsh-sudo
```

So is related to the solution, but not yet the full solution

**Comment by tsukker** [comment]
I faced the same problem.

So according to the comment of @AnimiVulpis (which I also confirmed on my environment), erasing the `fatal` error without moving current directory is what the full solution requires, right?

**Comment by NICHOLAS85** [comment]
Quick fix is to add `-C "$local_dir"` between git and show-ref:

`git -C "$local_dir" show-ref --verify --quiet refs/heads/main`

**Comment by tsukker** [comment]
> `git -C "$local_dir" show-ref --verify --quiet refs/heads/main`

This works for git repositories, but for binary releases the same `fatal` error occurs.

The following line gets no errors for both git repos and binary releases:

`if (( ! is_release )) && git -C $repo show-ref --verify --quiet refs/heads/main; then`

Are there any other things to consider?

**Comment by psprint** [comment]
The issue should be fixed, thanks.
