### ISSUE TITLE
$ICE not passed to atdelete hooks

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#429]
**Describe the bug**
`$ICE` is not passed to atdelete hooks breaking their functionality in annexes such as https://github.com/zinit-zsh/z-a-bin-gem-node as well as the `atdelete''` ice

For example, upon plugin deletion, https://github.com/zinit-zsh/z-a-bin-gem-node has a hook that is supposed to delete the plugins sbin entry at $ZPFX/bin. This fails to occur because `$ICE` has no value.

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Linux Nicks-Laptop 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux

**Comment by NICHOLAS85** [comment]
Looking at the code it seems ices are stored in `$ICE2` instead of `$ICE` which the rest of the code and annexes expect.

**Comment by psprint** [comment]
Thanks. Also, thanks for the linkbin annex!

**Comment by NICHOLAS85** [comment]
Thanks!
