### ISSUE TITLE
:zinit-tmp-subst-autoload() fails to deal with functions specified by path

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/zinit#441]
**Describe the bug**
The Zsh builtin `autoload` lets you autoload functions by passing their paths. However, when loading a plugin through Zinit, calling `autoload` in this fashion no longer works, because of a bug in `:zinit-tmp-subst-autoload`.

**To Reproduce**
 1. Create a minimal plugin with one hello-world function and `.plugin.zsh` file.
 1. In the `.plugin.zsh` file, autoload said function by specifying the absolute path to it:
    ```zsh
    autoload -Uz /absolute/path/to/hello-world
    ```
 1. Use Zinit to load the plugin.
 1. Try to call `hello-world`.
 1. Do `type -f hello-world`.

**Expected behavior**
Calling `hello-world` successfully runs the function and doing `type -f hello-world` shows the function body.

**Actual behavior**
Instead of defining a function `hello-world()`, what has actually happened is that Zinit has defined a function called `/absolute/path/to/hello-world()`. This obviously breaks our plugin.

**Workaround**
Replace all `autoload` statements with `builtin autoload`, thus bypassing `:zinit-tmp-subst-autoload()`.

**Comment by psprint** [comment]
The issue should be resolved now. I've also added a code that makes the absolute autoloading work for Zsh < 5.4.

**Comment by NICHOLAS85** [comment]
Commit 7afddbdde2c7f7bae038ae76658fb36b84fece9e seems to have broken `autoload +X` behavior in at least one plugin I use: https://github.com/Aloxaf/fzf-tab
The line in question: https://github.com/Aloxaf/fzf-tab/blob/c5b4ff2690e1580392a1d9c81aadf2540364efd5/fzf-tab.zsh#L269
`autoload +X -Uz _main_complete _approximate`
The functions are not being loaded like expected, breaking the functionality of the plugin later on.

**Comment by 7ocb** [comment]
I can confirm: the `fzf-tab` plugin gets broken.

**Comment by 7ocb** [comment]
@NICHOLAS85 you can change `.zinit` version to use like this (not sure if this canonical way but it seems to work), change the code zinit adds to .zshrc

```
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        pushd "$HOME/.zinit/bin" && \
        git checkout c27bf53f060d4584333ebdff8cfcd6aed60ca430 && \
        popd && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi
```

note the 


```
        pushd "$HOME/.zinit/bin" && \
        git checkout c27bf53f060d4584333ebdff8cfcd6aed60ca430 && \
        popd && \
```

then remove `.zinit` dir and restart shell.
