### ISSUE TITLE
Better way to unload a plugin when certain types of programs are running

### ISSUE THREAD

**Issue by smac89** [zdharma/zinit#451]
I just started using the `zinit` framework yesterday, and now I arrived at the reason why I decided to go with it in the first place and that is the conditional loading and unloading of plugins.

I use pyenv for managing local pythons on arch, so I installed pyenv plugin using:
```
# pyenv
zi ice atclone='PYENV_ROOT="$PWD" ./bin/pyenv init - > zpyenv.zsh' \
    atinit='export PYENV_ROOT="$PWD"' \
    atpull="%atclone" \
    as='command' pick='bin/pyenv' src="zpyenv.zsh" nocompile='!'
zi load pyenv/pyenv
```

The problem is that sometimes when I am trying to work with other programs (like `yay`, `makepkg`, `reflector`, etc) which have nothing to do with my local python, these programs might call other programs that will try to search for and find `python3` on the path. Because pyenv modifies the path, these programs will try to execute my local `python3`, and may fail because some module is not installed.

My current approach is to add the following `unload` condition:

```
unload='[[ "$(dirname $0)" = "/usr/bin" ]]'
```

This seems to unload `pyenv` whenever a command which exists in `/usr/bin` is run. However, I'm not sure if that's the correct way of doing this because replacing the above with `unload=[[ false ]]`, also does the same thing. In other words, I'm not sure how `unload` is supposed to be used 😝.

---

Ideally, what I would like to happen is that if I write a command which is not owned by my user, then pyenv should be unloaded while running that command, and then afterwards loaded again.

Is this possible? What are the alternatives?

Thanks

**Comment by psprint** [comment]
I think that you should load pyenv when entering your projects, e.g.: `load='[[ $PWD = */(project1|project2)(|/*) ]]' unload='[[ $PWD != */(project1|project2)(|/*) ]]'` .

**Comment by smac89** [comment]
The solution I went with was to modify pyenv.zsh to remove the `export PATH` line. Now when I need to use pyenv, I just run `pyenv exec python`. In addition, `pipenv` also does this to load a certain version of python
