### ISSUE TITLE
How to make zinit forget a plugin without deleting the plugin's folder

### ISSUE THREAD

**Issue by smac89** [zdharma/zinit#452]
Is this possible with zinit?

**Comment by pschmitt** [comment]
It's not clear to me what you want to achieve exactly but wouldn't `zinit unload` be enough?

**Comment by smac89** [comment]
Sorry perhaps it's my misunderstanding of how this framework works.

I am trying to use the `z-a-bin-gem-node` extension, and I'm trying to use the [`sbin`](https://zdharma.org/zinit/wiki/z-a-bin-gem-node/#5_sbingncneopath-to-binary_-_name-of-the-script) feature in another plugin.

In my zshrc, I initially had the following:

```zsh
# rbenv
zi ice atclone='RBENV_ROOT="$PWD" bin/rbenv init - > rbenv.zsh' \
    atpull="%atclone" \
    atinit='export RBENV_ROOT="$PWD"' \
    as='command' pick='bin/rbenv' src='rbenv.zsh' nocompile='!'
zi load rbenv/rbenv
```

When I decided to use the extension I mentioned, I changed the above zshrc file to:

```sh
zi light zinit-zsh/z-a-bin-gem-node

# rbenv
zi ice atclone='RBENV_ROOT="$PWD" bin/rbenv init - > rbenv.zsh' \
    atpull="%atclone" \
    atinit='export RBENV_ROOT="$PWD"' \
    sbin="c:rbenv" \
    as='command' pick='bin/rbenv' nocompile='!'
zi load rbenv/rbenv
```

I was expecting that this will create a script called `rbenv` in `$ZPFX/bin`, but it doesn't. I thought this was due to the fact that I had already added the `rbenv` and it was already loaded by `zinit`, so maybe the extension is not able to work properly and I should have added the extension first.

Furthermore, as you can see from the 2 snippets above, the first one sourced `rbenv.zsh` while the second one doesn't. Yet, whenever I run `zi report rbenv/rbenv`, the completions created by the `rbenv.zsh` file is always present, no matter if I go in and physically delete this file, it looks like `zinit` just remembers it. I run `zi cuinstall rbenv/rbenv`, then after I also run `zi creinstall rbenv/rbenv`, the completions come back.

So now, I'm asking 2 questions:

1. Is this the right way to use the extension, and is my expectation correct?
2. Apart from running `zi delete rbenv/rbenv`, is there any other way to tell `zinit` to reload everything about a plugin apart from deleting the already existing repo?

**Comment by smac89** [comment]
> It's not clear to me what you want to achieve exactly but wouldn't `zinit unload` be enough?

Actually it looks like `unload` does work for what I was trying to do.

Thanks a lot.
