### ISSUE TITLE
Customizing Paths bug

### ISSUE THREAD

**Issue by wbmins** [zdharma/zinit#463]
**Describe the bug**
my .zshrc
```shell
ZINIT[BIN_DIR]=~/.config/zinit/bin
ZINIT[HOME_DIR]=~/.config/zinit
ZINIT[PLUGINS_DIR]=~/.config/zinit/plugins
ZINIT[COMPLETIONS_DIR]=~/.config/zinit/completions
ZINIT[SNIPPETS_DIR]=~/.config/zinit/snippets
ZINIT[COMPINIT_OPTS]=~/.config/zinit
```
Open the terminal, it will still mkdir ~/.zinit 
I add `ZINIT[HOME_READY]=1`  in my .zshrc.it will not mkdir
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): Linux ... 5.10.3-arch1-1 #1 SMP PREEMPT Sun, 27 Dec 2020 10:50:46 +0000 x86_64 GNU/Linux

**Additional context**

**Comment by fhuitelec** [comment]
:information_source: For people stumbling on this issue, this is documented [here](https://github.com/zdharma/zinit#customizing-paths).

And for those in a hurry and wanting some XDG Base Directory compliant directories<sup>1</sup>:

```shell
# In your .zshrc
# Let's assume you have installed zinit via:
# git clone git@github.com:zdharma/zinit.git $HOME/.local/share/zinit

declare -A ZINIT

export ZINIT[HOME_DIR]=$HOME/.cache/zinit
export ZINIT[PLUGINS_DIR]=$HOME/.cache/zinit/plugins
export ZINIT[COMPLETIONS_DIR]=$HOME/.cache/zinit/completions
export ZINIT[SNIPPETS_DIR]=$HOME/.cache/zinit/snippets
export ZINIT[ZCOMPDUMP_PATH]=$HOME/.cache/zsh/.zcompdump
export ZPFX=$HOME/.cache/zinit/polaris

source "$HOME/.local/share/zinit/zinit.zsh"
```

---

<sup>1</sup> This is the reason I stumbled upon this in the first place, sorry for hijacking this issue.
