### ISSUE TITLE
kubectl completions

### ISSUE THREAD

**Issue by HenriAW** [zdharma/zinit#478]
Hi all,

I'm trying to get kubectl completions working with zinit and I feel I'm missing the nice way to do this. Currently I'm just running:
```zsh
autoload -Uz compinit
compinit
source <(kubectl completion zsh)
alias k=kubectl
complete -F __start_kubectl k
```
and haven't been able to find a nice way to get this functionality working quickly using zinit. I've searched quite a bit for examples but haven't been able to find any. Would someone be able to give an example of a nice "zinit" way to do this?

**Comment by pschmitt** [comment]
#260

**Comment by HenriAW** [comment]
Thanks, I had seen that although I couldn't seem to get that setup to work. I did however find that just adding `zpcompinit` to my .zshrc worked.
I assume this is loading things from some kind of cache since at no other point in my .zshrc am I loading any completion plugin or even mentioning kubernetes, but I haven't been able to find any documentation on how this is working.
It's a lot quicker my other method though which is useful. Can anyone explain how this works and why?
