### ISSUE TITLE
How install from script in a docker image?

### ISSUE THREAD

**Issue by ddnexus** [zdharma/zinit#484]
I didn't find any information about how to install the plugin in a docker container from script. 

I've just find a reference that look interesting, but I have no idea about how to use/trigger that in an installation script.

`@zinit-scheduler` with "burst" 
> ...handy if e.g. a docker image starts up and
> needs to install all turbo-mode plugins without any hesitation
> (delay), i.e. "burst" allows to run package installations from            
> script, not from prompt

Right now I am installing `zinit` with 
```
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
```
that writes its lines in an empty `.zshrc`
then I do
```
COPY zshrc-additions /tmp/
RUN cat /tmp/zshrc-additions >> /home/$user/.zshrc
```
so adding the missing configuration and the plugins after the initial `zinit` setup lines. But then the added plugins will get installed only when the user will run the docker container.

How can I script the whole installation (possibly with the same nice feedback of the plugin installation)?

**Comment by ddnexus** [comment]
@mnowotnik... I just read your #483 and you seem quite knowledgeable about `@zinit-scheduler`. Do you have some clue about using it or triggering it to solve my problem?

**Comment by pschmitt** [comment]
You probably want to use `@zinit-scheduler burst`.

But there's [a gotcha])(https://github.com/zdharma/zinit/issues/401)

**Comment by ddnexus** [comment]
@pschmitt thank you. Indeed that is the very first thing I tried, and I hit the same problem of the `atclone` ice that I use to install `fzf`. That is why I created this issue, thinking it was not the proper way to use it (and maybe it is still not the right one).

However, just yesterday, tinkering with the same stuff again and again, I've discovered that the `--shinstdin` (`-s`) option makes the ice work in my case. This is what happens to work in a `sh` script, exactly as it would interactively:

```
docker run --rm -v my_home:/home/$USER my_image env TERM="${TERM}" zsh -isc "@zinit-scheduler burst"
```

Notice: the `env TERM="${TERM}"` makes it work as in a real terminal, or you will get tput errors on certain plugins; and the `-s` definitely make zinit run the ices.

Please, could you confirm whether it works also in your case?

**Comment by ddnexus** [comment]
Just tried to use it from inside the docker container and it works too:

```dockerfile
ARG term
RUN env TERM="$term" zsh -isc "@zinit-scheduler burst"
```

**Comment by ddnexus** [comment]
Notice that without the `env TERM="$term"`, besides the tput error, it will also skip installing many plugins in my case. Not sure why.

**Comment by pschmitt** [comment]
Nice find, @ddnexus!

> Please, could you confirm whether it works also in your case?

It does seem to work for the direnv example! Thanks!

For reference here's what I tested it with:

- `Dockerfile`

```Dockerfile
FROM ubuntu:latest

RUN apt-get update && \
  DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y curl git zsh build-essential golang vim && \
  rm -rf /var/lib/apt/lists/* && \
  adduser --disabled-password --shell /bin/zsh --gecos '' user

USER user
WORKDIR /home/user

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)" && \
  echo '\nfor file in /config/*; do source $file; done\nzpcompinit' >> /home/user/.zshrc

ADD ./config.zsh /config/config.zsh

ARG TERM

RUN TERM=${TERM:-screen-256color} zsh -isc "@zinit-scheduler burst"

ENTRYPOINT ["/bin/zsh"]
```

- `config.zsh`

```zsh
zinit as"program" make'!' atclone'./direnv hook zsh > zhook.zsh' \
  atpull'%atclone' pick"direnv" src"zhook.zsh" for \
    direnv/direnv
```

**Comment by ddnexus** [comment]
Great to know! Then we may probably want close both issues.

**Comment by black7375** [comment]
It seems to be incomplete. A lot of turbo mode's plugins don't work.

---
My Docker File
https://github.com/black7375/BlaCk-Void-Zsh/blob/master/Dockerfile

```shell
docker pull alstjr7375/bvzsh:latest
docker run --rm -it alstjr7375/bvzsh
```
