### ISSUE TITLE
How to load ogham/exa completion?

### ISSUE THREAD

**Issue by crazy-matt** [zdharma/zinit#485]
Hi,

I'm trying to get the [exa](https://github.com/ogham/exa/blob/master/completions/completions.zsh) completion working without having to fully install exa with Zinit, as I install it separately with my plugin manager.

#### My last unsuccessful attempt was this one:
```zsh
zinit ice lucid wait'0a' as'completion' \
  mv'completions.zsh -> _exa'
zinit snippet https://github.com/ogham/exa/blob/master/completions/completions.zsh
```

#### Behavior:
The snippet get downloaded successfully under the Zinit `snippets` folder. But I've never been able to get the `_exa` file which should be in the Zinit `completions` folder.

Does anyone knows how to achieve this please?

**Comment by NICHOLAS85** [comment]
Try using the raw link: https://raw.githubusercontent.com/ogham/exa/master/completions/completions.zsh

**Comment by crazy-matt** [comment]
Thanks @NICHOLAS85 for helping.
It also refuses to work with raw link, see the result below compared to another completion working well without raw link:
```zsh
Setting up snippet: https://raw.githubusercontent.com/ogham/exa/master/completions
Downloading `https://raw.githubusercontent.com/ogham/exa/master/completions` (with curl, wget, lftp)…
################################################################################################################################ 100.0%

Setting up snippet: https://github.com/TheLocehiliosan/yadm/blob/master
Downloading `https://github.com/TheLocehiliosan/yadm/blob/master` (with curl, wget, lftp)…
################################################################################################################################ 100.0%
Installed 1 completions. They are stored in $INSTALLED_COMPS array.
```

#### Their respective configurations below:
```zsh
zinit ice lucid wait"0a" as"completion" \
  mv"completions.zsh -> _exa"
zinit snippet https://raw.githubusercontent.com/ogham/exa/master/completions/completions.zsh

zinit ice lucid wait"0b" as"completion" blockf has"yadm"
zinit snippet https://github.com/TheLocehiliosan/yadm/blob/master/completion/zsh/_yadm
```

**Comment by crazy-matt** [comment]
Is there a way to enable a debug mode to see what's going on? `typeset -g ZPLG_MOD_DEBUG=1` does not seem to provide any additional output.

**Comment by black7375** [comment]
[bat](https://github.com/sharkdp/bat) seems to be created dynamically at release.
https://github.com/sharkdp/bat/blob/master/assets/completions/bat.zsh.in

```shell
    zplugin ice wait"2" as"command" from"gh-r" lucid \
            mv"bat* -> bat" pick"bat/bat" atload"alias cat=bat"
    zplugin light sharkdp/bat

    # This not work.
    zplugin ice wait"2" as"completion" from"gh-r" lucid \
            mv"bat/autocomplete/bat.zsh -> _bat" pick"bat/autocomplete/_bat"
    zplugin light sharkdp/bat
```

What should I do in this case?

**Comment by pschmitt** [comment]
Here's what I have for bat:

```zsh
zinit as"command" from"gh-r" \
  for \
    atclone"cp -vf bat*/autocomplete/bat.zsh _bat; \
            cp -vf bat*/bat.1 $ZPFX/man/man1" \
    atpull"%atclone" \
    atdelete"rm -f $ZPFX/man/man1/bat.1" \
    sbin"bat*/bat -> bat" \
  @sharkdp/bat
```

**Comment by black7375** [comment]
@pschmitt  thanks!! :+1:

**Comment by crazy-matt** [comment]
Thanks a lot @pschmitt! It worked for me too.
I just precise here for future readers that you need to install [z-a-patch-dl](https://github.com/zinit-zsh/z-a-patch-dl) to be able to use the dl command. And I've made it working only for completion installation that way:
```zsh
zinit as"completion" for \
  dl"https://raw.githubusercontent.com/ogham/exa/master/completions/completions.zsh -> _exa" \
  @ogham/exa
```

**Comment by stevenguh** [comment]
Here is what I have to load autocomplete without using z-a-patch-dl
```
zinit lucid wait light-mode as"program" from"gh-r" for \
    atclone"cp -vf bat*/autocomplete/bat.zsh _bat" \
    atpull"%atclone" \
    mv"bat* -> bat" pick"bat/bat" \
    @sharkdp/bat \
    \
    atclone"cp -vf completions/exa.zsh _exa" \
    atpull"%atclone" \
    mv"bin/exa* -> exa" \
    @ogham/exa
```
