### ISSUE TITLE
ice eval keyword

### ISSUE THREAD

**Issue by black7375** [zdharma/zinit#487]
**Is your feature request related to a problem? Please describe.**
When I set up a plug-in, I often use eval and the amount of code gets longer.
```shell
zinit ice wait"2" as"command" from"gh-r" lucid \
          mv"zoxide* -> zoxide" atclone"./zoxide init zsh > init.zsh" \
          atpull"%atclone" src"init.zsh" nocompile'!'
zinit light ajeetdsouza/zoxide

zinit ice wait"2" atclone"dircolors -b LS_COLORS > init.zsh" lucid \
          atpull"%atclone" pick"init.zsh" nocompile'!' \
          atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS
```

**Describe the solution you'd like**
I want `eval` keyword.
```shell
zinit ice wait"2" as"command" from"gh-r" lucid \
          mv"zoxide* -> zoxide" eval"./zoxide init zsh"
zinit light ajeetdsouza/zoxide

zinit ice wait"2" eval"dircolors -b LS_COLORS" lucid \
          atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS
```

**Describe alternatives you've considered**
eval caching samples
https://github.com/mroth/evalcache
https://github.com/marlonrichert/zsh-snap/blob/main/functions/.znap.eval

**Additional context**
#68

**Comment by NICHOLAS85** [comment]
Seeing this I decided to try to make an Zsh-annex to provide the functionality mentioned here and in #68. My first iteration can be found here https://github.com/NICHOLAS85/z-a-eval. To use it simply load the plugin then use the `eval` ice just like you described:
```zsh
zinit light NICHOLAS85/z-a-eval

zinit ice wait"2" as"command" from"gh-r" lucid \
          mv"zoxide* -> zoxide" eval"./zoxide init zsh"
zinit light ajeetdsouza/zoxide

zinit ice wait"2" eval"dircolors -b LS_COLORS" lucid \
          atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS
```
Let me know what you think and if you run into any issues!

**Comment by black7375** [comment]
That's what I wanted!

I don't have time on weekends, so I'll post an issue next week if there's a problem after the test.
Thank you for the good plug-in.
