### ISSUE TITLE
"dummy" plugin OR how to use only zinit scheduling 

### ISSUE THREAD

**Issue by Stefanqn** [zdharma/zinit#500]
**Is your feature request related to a problem? Please describe.**
I'm using zinit in turbo mode. As described in the documentation, I load fast-syntax-highlighting with
```
zinit wait"0b" lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay" \
    zdharma/fast-syntax-highlighting \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
 blockf \
    zsh-users/zsh-completions
```
Some aws completion command now depends on `zpcompinit` and needs to be executed afterwards, at 0c.
Currently, I'm downloading a completely unrelated plugin to get this done:
```
needsCompletion "aws" && zi wait"0c" lucid for \
 has'aws_completer' as'null' \
 id-as'aws_completion' \
 atload'autoload -Uz bashcompinit && bashcompinit && complete -C "$(which aws_completer)" aws' \
     'remind101/assume-role' # this is wrong !!!
```

**Describe the solution you'd like**
Some functionality to do this without downloading `assume-role`

**Comment by bbenzikry** [comment]
You should be able to use ``zdharma/null``

**Comment by Stefanqn** [comment]
true. Wouldn't it make sense to introduce `null` as something similar, without the network/git overhead?

**Comment by bbenzikry** [comment]
It probably would make sense - how badly does this affect you? I don't feel like it makes my startup slow and I've got quite a few calls to zdharma/null

**Comment by Stefanqn** [comment]
yeah, it's not too bad speed-wise.

**Comment by NICHOLAS85** [comment]
I believe you can use `/dev/null` instead of `zdharma/null` if you want something without a network/git overhead.

**Comment by bbenzikry** [comment]
Are you sure @NICHOLAS85? Can you add an example? just got
``
(anon):cd: not a directory: /dev/null
``

**Comment by NICHOLAS85** [comment]
While I'm here try using the nocd ice, I'll go look for an example in a moment

**Comment by bbenzikry** [comment]
Yeah, thought of that - the problem with this comes when it's a command that needs to persist something
```bash
zinit lucid for \
id-as'testing-testing' nocd atinit'touch .something' /dev/null
```

.something will not be created under ~/.zinit/plugins/testing-testing, which is what I would expect even without cloning

**Comment by NICHOLAS85** [comment]
Interesting, I might've misremembered the support for /dev/null, maybe it was broken after a while. The only things I can suggest is either creating a local 'null' plugin like suggested earlier in issue https://github.com/zdharma/zinit/issues/68 or using zdharma/null(or your own null repo)

**Comment by psprint** [comment]
`/dev/null` is supported as local-file *snippet*, i.e.:
```zsh
zinit ice atinit'print Hi' id-as'my-snippet'
zinit snippet /dev/null
```

or:

```zsh
zinit  atinit'print Hi' id-as'my-snippet' is-snippet for /dev/null
```

**Comment by Stefanqn** [comment]
Cool, is it possible to call `zinit create null` headless / in batch mode? 
` [[ ! -d ${ZINIT[PLUGINS_DIR]}/null ]] && zinit create null` blocks for input

**Comment by Stefanqn** [comment]
actually, I realized that it's not necessary, since also snippets create their own folder, so this works:
`zinit wait"0c" lucid  is-snippet atclone'oc completion zsh > _oc' atpull"%atclone" id-as'oc_completion' atload'source _oc' for /dev/null`
