### ISSUE TITLE
How can I do to remove extra white line between two command lines when I set single-line prompts. 

### ISSUE THREAD

**Issue by Skyearn** [zdharma/zinit#507]
**Is your feature request related to a problem? Please describe.**
I set ~/.zshrc as #228 for single-line prompts, then this caused a new problem, there are extra white line between two command lines. and I have no way to solve this problem.

**Describe the solution you'd like**
It's mine:
![](https://user-images.githubusercontent.com/29571915/114839263-26094200-9e08-11eb-9806-0ef701b596d4.png)
I want change it like this:
![](https://cloud.githubusercontent.com/assets/147409/25740894/294b9c20-3191-11e7-947f-b3ac1597f69f.png)

**Comment by pschmitt** [comment]
This is not a zinit issue, but one of whatever prompt you are using ([pure?](https://github.com/sindresorhus/pure))

**Comment by Skyearn** [comment]
> This is not a zinit issue, but one of whatever prompt you are using ([pure?](https://github.com/sindresorhus/pure))

yes, I'm using pure. are there other prompt recommended?

**Comment by pschmitt** [comment]
Please raise this issue with the pure guys, this here is zinit.

Anyway. There's plenty of alternatives:
- https://github.com/romkatv/powerlevel10k
- https://starship.rs/

**Comment by Skyearn** [comment]
OK, thanks.

i！

> 在 2021年4月22日，18:31，Philipp Schmitt ***@***.***> 写道：
> 
> alternatives
